SELECT MAX(id) FROM posts;

-- Insert sample posts
INSERT INTO posts (user_id, image_url, caption) VALUES
(1, 'https://example.com/image1.jpg', 'First post by User One'),
(2, 'https://example.com/image2.jpg', 'Exciting post from User Two'),
(3, 'https://example.com/image3.jpg', 'Great vibes! #life'),
(4, 'https://example.com/image4.jpg', 'Final post for testing.'),
(1, 'https://example.com/image1.jpg', 'Chilling in the Arctic 🐧'),
(9, 'https://example.com/image2.jpg', 'Skyline dreams! 🌃'),
(3, 'https://example.com/image3.jpg', 'Another peak conquered 🏔️'),
(3, 'https://example.com/image20.jpg', 'This is just the beginning...');

INSERT INTO posts (user_id, image_url, caption)
VALUES (3, 'https://example.com/image21.jpg', 'Another peak conquered 🏔️');

SELECT * FROM posts;
SELECT * FROM posts WHERE id = 466;

UPDATE posts
SET caption = 'Updated caption for this awesome post!'
WHERE id = 1;

DELETE FROM posts WHERE id = 484;


INSERT INTO posts (user_id, image_url, caption) VALUES
(1, 'https://example.com/post1.jpg', 'Exploring the beautiful streets of Paris, living my best travel life! #Paris #Wanderlust'),
(2, 'https://example.com/post2.jpg', 'Hiking through the Swiss Alps was a dream come true. The views were breathtaking! #AdventureAwaits #SwissAlps'),
(3, 'https://example.com/post3.jpg', 'Made it to the top of Machu Picchu! Feeling on top of the world. #Peru #MachuPicchu'),
(4, 'https://example.com/post4.jpg', 'Strolling along the beaches of Bali. The sand, the sea, the sunset – pure bliss. #Bali #BeachVibes'),
(5, 'https://example.com/post5.jpg', 'Catching a glimpse of the Northern Lights in Iceland. Magical experience! #Iceland #NorthernLights'),
(6, 'https://example.com/post6.jpg', 'Wandered through the vibrant markets of Marrakech today. So much color and life! #Marrakech #TravelGoals'),
(7, 'https://example.com/post7.jpg', 'Exploring the ancient ruins of Rome. So much history in one place. #Rome #History'),
(8, 'https://example.com/post8.jpg', 'A peaceful afternoon in the lavender fields of Provence. This place is a dream! #Provence #LavenderFields'),
(9, 'https://example.com/post9.jpg', 'Kayaking in the crystal-clear waters of the Maldives. It doesn’t get better than this! #Maldives #TropicalParadise'),
(10, 'https://example.com/post10.jpg', 'Admiring the stunning landscapes in New Zealand. Nature at its finest. #NewZealand #NatureLover'),
(11, 'https://example.com/post11.jpg', 'Caught a gorgeous sunset in Santorini. Couldn’t ask for a better view! #Santorini #SunsetLover'),
(12, 'https://example.com/post12.jpg', 'Trekking through the Amazon Rainforest was an unforgettable experience. So much to see here! #Amazon #RainforestAdventure'),
(13, 'https://example.com/post13.jpg', 'Exploring the beautiful temples of Kyoto. A peaceful escape in the heart of Japan. #Kyoto #Japan'),
(14, 'https://example.com/post14.jpg', 'Spent the day soaking up the sun on the beaches of Costa Rica. Pure relaxation! #CostaRica #BeachTime'),
(15, 'https://example.com/post15.jpg', 'Took a boat tour through the stunning fjords of Norway today. Truly a sight to behold. #Norway #FjordViews'),
(16, 'https://example.com/post16.jpg', 'Had the most amazing time snorkeling in the Great Barrier Reef. A world of color beneath the waves! #Australia #GreatBarrierReef'),
(17, 'https://example.com/post17.jpg', 'Toured the majestic temples of Angkor Wat. Such an awe-inspiring experience. #AngkorWat #Cambodia'),
(18, 'https://example.com/post18.jpg', 'Exploring the city of lights, Paris. The Eiffel Tower never gets old! #Paris #EiffelTower'),
(19, 'https://example.com/post19.jpg', 'Taking in the breathtaking views from the top of Table Mountain in Cape Town. #SouthAfrica #TableMountain'),
(20, 'https://example.com/post20.jpg', 'Caught an amazing sunrise in the Sahara Desert. The endless dunes are just mesmerizing. #SaharaDesert #Sunrise'),
(21, 'https://example.com/post21.jpg', 'Visited the ancient city of Petra today. The architecture is mind-blowing. #Petra #Jordan'),
(22, 'https://example.com/post22.jpg', 'Adventuring through the jungles of Costa Rica. Nature at its wildest! #CostaRica #JungleAdventure'),
(23, 'https://example.com/post23.jpg', 'Exploring the beautiful island of Santorini. The blue and white buildings are stunning! #Santorini #GreekIslands'),
(24, 'https://example.com/post24.jpg', 'Enjoying some quiet time at the iconic Lake Louise in Canada. #Canada #LakeLouise'),
(25, 'https://example.com/post25.jpg', 'Trekking through the stunning landscapes of Patagonia in Argentina. Nature at its best. #Patagonia #Argentina'),
(26, 'https://example.com/post26.jpg', 'Relaxing on the beautiful beaches of Thailand. A perfect day in paradise! #Thailand #BeachVibes'),
(27, 'https://example.com/post27.jpg', 'Taking in the incredible views from the Grand Canyon. Nature is truly awe-inspiring. #GrandCanyon #NatureLover'),
(28, 'https://example.com/post28.jpg', 'Exploring the streets of Barcelona. The city is full of energy and culture! #Barcelona #CityLife'),
(29, 'https://example.com/post29.jpg', 'Visited the incredible city of Cairo today. The Pyramids are beyond impressive. #Cairo #Pyramids'),
(30, 'https://example.com/post30.jpg', 'Snorkeling with sea turtles in Hawaii. It’s always an adventure here! #Hawaii #SeaTurtles'),
(31, 'https://example.com/post31.jpg', 'Spent the day exploring the stunning island of Maui. It’s paradise on earth! #Maui #IslandLife'),
(32, 'https://example.com/post32.jpg', 'Took a scenic hike to a waterfall in Costa Rica today. Nature always knows how to surprise me. #CostaRica #Waterfall'),
(33, 'https://example.com/post33.jpg', 'Visited the beautiful city of Amsterdam today. The canals are simply picturesque! #Amsterdam #Canals'),
(34, 'https://example.com/post34.jpg', 'Had an incredible experience zip-lining through the jungles of Belize. #Belize #Adventure'),
(35, 'https://example.com/post35.jpg', 'Exploring the bustling streets of Tokyo. This city is always alive with energy! #Tokyo #CityVibes'),
(36, 'https://example.com/post36.jpg', 'Went on a safari in Kenya and spotted the Big Five! Truly an unforgettable experience. #Kenya #Safari'),
(37, 'https://example.com/post37.jpg', 'Enjoying the beauty of the Swiss lakes. Nature has a way of calming the soul. #Switzerland #Lakeside'),
(38, 'https://example.com/post38.jpg', 'Relaxing by the crystal-clear waters of Bora Bora. Couldn’t ask for a better paradise. #BoraBora #TropicalGetaway'),
(39, 'https://example.com/post39.jpg', 'Hiking the Inca Trail in Peru was one of the most rewarding challenges. #IncaTrail #Peru'),
(40, 'https://example.com/post40.jpg', 'Enjoying a delicious meal at a local restaurant in Vietnam. The food is out of this world! #Vietnam #Foodie'),
(41, 'https://example.com/post41.jpg', 'Had an amazing time exploring the temples of Bagan in Myanmar. So much history in one place. #Bagan #Myanmar'),
(42, 'https://example.com/post42.jpg', 'Soaking in the beauty of the Blue Lagoon in Iceland. The water is magical. #Iceland #BlueLagoon'),
(43, 'https://example.com/post43.jpg', 'Enjoying the vibrant nightlife in Bangkok. There’s always something to do here! #Bangkok #Nightlife'),
(44, 'https://example.com/post44.jpg', 'Taking a peaceful walk through the cherry blossoms in Japan. Pure serenity. #Japan #CherryBlossoms'),
(45, 'https://example.com/post45.jpg', 'Hiking through the beautiful forests of Vancouver. Nature at its finest! #Vancouver #ForestHike'),
(46, 'https://example.com/post46.jpg', 'Exploring the stunning beaches of Fiji. This place is paradise! #Fiji #BeachLife'),
(47, 'https://example.com/post47.jpg', 'Spent the day cycling through the picturesque streets of Copenhagen. #Copenhagen #CyclingAdventures'),
(48, 'https://example.com/post48.jpg', 'Walking through the medieval streets of Prague. The city is full of charm. #Prague #CityWalk'),
(49, 'https://example.com/post49.jpg', 'Admiring the view of the Colosseum in Rome. Such an iconic landmark. #Rome #Colosseum'),
(50, 'https://example.com/post50.jpg', 'Exploring the hidden gems of the Amalfi Coast in Italy. This place is magical. #AmalfiCoast #TravelGoals');

INSERT INTO posts (user_id, image_url, caption) VALUES
(212, 'https://example.com/post1.jpg', 'Exploring the beautiful streets of Paris, living my best travel life! #Paris #Wanderlust'),
(212, 'https://example.com/post2.jpg', 'Hiking through the Swiss Alps was a dream come true. The views were breathtaking! #AdventureAwaits #SwissAlps'),
(811, 'https://example.com/post3.jpg', 'Made it to the top of Machu Picchu! Feeling on top of the world. #Peru #MachuPicchu'),
(811, 'https://example.com/post4.jpg', 'Strolling along the beaches of Bali. The sand, the sea, the sunset – pure bliss. #Bali #BeachVibes'),
(121, 'https://example.com/post5.jpg', 'Catching a glimpse of the Northern Lights in Iceland. Magical experience! #Iceland #NorthernLights'),
(212, 'https://example.com/post6.jpg', 'Wandered through the vibrant markets of Marrakech today. So much color and life! #Marrakech #TravelGoals'),
(212, 'https://example.com/post7.jpg', 'Exploring the ancient ruins of Rome. So much history in one place. #Rome #History'),
(212, 'https://example.com/post8.jpg', 'A peaceful afternoon in the lavender fields of Provence. This place is a dream! #Provence #LavenderFields'),
(1279, 'https://example.com/post9.jpg', 'Kayaking in the crystal-clear waters of the Maldives. It doesn’t get better than this! #Maldives #TropicalParadise'),
(1279, 'https://example.com/post10.jpg', 'Admiring the stunning landscapes in New Zealand. Nature at its finest. #NewZealand #NatureLover'),
(35, 'https://example.com/post11.jpg', 'Caught a gorgeous sunset in Santorini. Couldn’t ask for a better view! #Santorini #SunsetLover'),
(1279, 'https://example.com/post12.jpg', 'Trekking through the Amazon Rainforest was an unforgettable experience. So much to see here! #Amazon #RainforestAdventure'),
(455, 'https://example.com/post13.jpg', 'Exploring the beautiful temples of Kyoto. A peaceful escape in the heart of Japan. #Kyoto #Japan'),
(1279, 'https://example.com/post14.jpg', 'Spent the day soaking up the sun on the beaches of Costa Rica. Pure relaxation! #CostaRica #BeachTime'),
(121, 'https://example.com/post15.jpg', 'Took a boat tour through the stunning fjords of Norway today. Truly a sight to behold. #Norway #FjordViews'),
(1143, 'https://example.com/post16.jpg', 'Had the most amazing time snorkeling in the Great Barrier Reef. A world of color beneath the waves! #Australia #GreatBarrierReef'),
(1143, 'https://example.com/post17.jpg', 'Toured the majestic temples of Angkor Wat. Such an awe-inspiring experience. #AngkorWat #Cambodia'),
(806, 'https://example.com/post18.jpg', 'Exploring the city of lights, Paris. The Eiffel Tower never gets old! #Paris #EiffelTower'),
(909, 'https://example.com/post19.jpg', 'Taking in the breathtaking views from the top of Table Mountain in Cape Town. #SouthAfrica #TableMountain'),
(909, 'https://example.com/post20.jpg', 'Caught an amazing sunrise in the Sahara Desert. The endless dunes are just mesmerizing. #SaharaDesert #Sunrise'),
(1103, 'https://example.com/post21.jpg', 'Visited the ancient city of Petra today. The architecture is mind-blowing. #Petra #Jordan'),
(1279, 'https://example.com/post22.jpg', 'Adventuring through the jungles of Costa Rica. Nature at its wildest! #CostaRica #JungleAdventure'),
(1303, 'https://example.com/post23.jpg', 'Exploring the beautiful island of Santorini. The blue and white buildings are stunning! #Santorini #GreekIslands'),
(140, 'https://example.com/post24.jpg', 'Enjoying some quiet time at the iconic Lake Louise in Canada. #Canada #LakeLouise'),
(155, 'https://example.com/post25.jpg', 'Trekking through the stunning landscapes of Patagonia in Argentina. Nature at its best. #Patagonia #Argentina'),
(64, 'https://example.com/post26.jpg', 'Relaxing on the beautiful beaches of Thailand. A perfect day in paradise! #Thailand #BeachVibes'),
(1012, 'https://example.com/post27.jpg', 'Taking in the incredible views from the Grand Canyon. Nature is truly awe-inspiring. #GrandCanyon #NatureLover'),
(1280, 'https://example.com/post28.jpg', 'Exploring the streets of Barcelona. The city is full of energy and culture! #Barcelona #CityLife'),
(19, 'https://example.com/post29.jpg', 'Visited the incredible city of Cairo today. The Pyramids are beyond impressive. #Cairo #Pyramids'),
(1012, 'https://example.com/post30.jpg', 'Snorkeling with sea turtles in Hawaii. It’s always an adventure here! #Hawaii #SeaTurtles'),
(1012, 'https://example.com/post31.jpg', 'Spent the day exploring the stunning island of Maui. It’s paradise on earth! #Maui #IslandLife'),
(1279, 'https://example.com/post32.jpg', 'Took a scenic hike to a waterfall in Costa Rica today. Nature always knows how to surprise me. #CostaRica #Waterfall'),
(33, 'https://example.com/post33.jpg', 'Visited the beautiful city of Amsterdam today. The canals are simply picturesque! #Amsterdam #Canals'),
(1279, 'https://example.com/post34.jpg', 'Had an incredible experience zip-lining through the jungles of Belize. #Belize #Adventure'),
(252, 'https://example.com/post35.jpg', 'Exploring the bustling streets of Tokyo. This city is always alive with energy! #Tokyo #CityVibes'),
(960, 'https://example.com/post36.jpg', 'Went on a safari in Kenya and spotted the Big Five! Truly an unforgettable experience. #Kenya #Safari'),
(270, 'https://example.com/post37.jpg', 'Enjoying the beauty of the Swiss lakes. Nature has a way of calming the soul. #Switzerland #Lakeside'),
(100, 'https://example.com/post38.jpg', 'Relaxing by the crystal-clear waters of Bora Bora. Couldn’t ask for a better paradise. #BoraBora #TropicalGetaway'),
(100, 'https://example.com/post39.jpg', 'Hiking the Inca Trail in Peru was one of the most rewarding challenges. #IncaTrail #Peru'),
(100, 'https://example.com/post40.jpg', 'Enjoying a delicious meal at a local restaurant in Vietnam. The food is out of this world! #Vietnam #Foodie'),
(100, 'https://example.com/post41.jpg', 'Had an amazing time exploring the temples of Bagan in Myanmar. So much history in one place. #Bagan #Myanmar'),
(100, 'https://example.com/post42.jpg', 'Soaking in the beauty of the Blue Lagoon in Iceland. The water is magical. #Iceland #BlueLagoon'),
(100, 'https://example.com/post43.jpg', 'Enjoying the vibrant nightlife in Bangkok. There’s always something to do here! #Bangkok #Nightlife'),
(100, 'https://example.com/post44.jpg', 'Taking a peaceful walk through the cherry blossoms in Japan. Pure serenity. #Japan #CherryBlossoms'),
(353, 'https://example.com/post45.jpg', 'Hiking through the beautiful forests of Vancouver. Nature at its finest! #Vancouver #ForestHike'),
(1360, 'https://example.com/post46.jpg', 'Exploring the stunning beaches of Fiji. This place is paradise! #Fiji #BeachLife'),
(75, 'https://example.com/post47.jpg', 'Spent the day cycling through the picturesque streets of Copenhagen. #Copenhagen #CyclingAdventures'),
(138, 'https://example.com/post48.jpg', 'Walking through the medieval streets of Prague. The city is full of charm. #Prague #CityWalk'),
(138, 'https://example.com/post49.jpg', 'Admiring the view of the Colosseum in Rome. Such an iconic landmark. #Rome #Colosseum'),
(431, 'https://example.com/post50.jpg', 'Exploring the hidden gems of the Amalfi Coast in Italy. This place is magical. #AmalfiCoast #TravelGoals');

INSERT INTO posts (user_id, image_url, caption) VALUES
(232, 'https://example.com/japan1.jpg', 'Exploring the bustling streets of Shibuya. Tokyo never sleeps! #Tokyo #Shibuya #CityLife'),
(232, 'https://example.com/japan2.jpg', 'Caught a glimpse of Mount Fuji while hiking. Simply majestic! #MountFuji #Japan #NatureLover'),
(232, 'https://example.com/japan3.jpg', 'Had the most amazing sushi in Tsukiji Market. Best food I’ve ever had! #Tokyo #SushiLover'),
(100, 'https://example.com/japan4.jpg', 'Visited the beautiful Golden Pavilion in Kyoto today. Stunning architecture! #Kyoto #GoldenPavilion'),
(232, 'https://example.com/japan5.jpg', 'Exploring the peaceful gardens at Kinkaku-ji. Kyoto’s beauty is beyond words. #Kyoto #Kinkakuji'),
(255, 'https://example.com/japan6.jpg', 'Took a boat ride through the canals of Tokyo. The city’s energy is unbeatable! #Tokyo #CanalRide'),
(255, 'https://example.com/japan7.jpg', 'Walking through the colorful streets of Harajuku. This place is full of life and fashion! #Tokyo #Harajuku'),
(255, 'https://example.com/japan8.jpg', 'Spent the day in Nara, feeding the friendly deer at Nara Park. What an experience! #Nara #Japan #TravelDiaries'),
(226, 'https://example.com/japan9.jpg', 'Admiring the beauty of the cherry blossoms in full bloom. A perfect spring day in Japan! #Sakura #CherryBlossoms'),
(226, 'https://example.com/japan10.jpg', 'Exploring the serene temples of Kyoto. The peace and quiet are magical. #Kyoto #JapaneseTemples'),
(226, 'https://example.com/japan11.jpg', 'Visited the incredible Fushimi Inari Taisha and walked through thousands of red torii gates. #Kyoto #InariTaisha'),
(100, 'https://example.com/japan12.jpg', 'Had a relaxing day in the hot springs of Hakone. So rejuvenating! #Hakone #Onsen'),
(232, 'https://example.com/japan13.jpg', 'Riding the Shinkansen to Osaka. Can’t wait to explore the city! #Shinkansen #Osaka #JapanAdventure'),
(226, 'https://example.com/japan14.jpg', 'Exploring the historic streets of Kanazawa. This city has such charm! #Kanazawa #JapaneseHeritage'),
(226, 'https://example.com/japan15.jpg', 'Tasting street food in Osaka. Takoyaki and Okonomiyaki are a must! #Osaka #JapaneseFood'),
(100, 'https://example.com/japan16.jpg', 'Wandering around the peaceful temples in Kamigamo Shrine. #Kyoto #KamigamoShrine #JapanTravel'),
(325, 'https://example.com/japan17.jpg', 'Trekking through the Japanese Alps. Stunning landscapes! #JapanAlps #NatureAdventure'),
(226, 'https://example.com/japan18.jpg', 'Took a day trip to Hiroshima and visited the Peace Memorial Park. Such a humbling experience. #Hiroshima #Peace'),
(325, 'https://example.com/japan19.jpg', 'Exploring the vibrant streets of Osaka. This city is full of surprises! #Osaka #CityExploration'),
(226, 'https://example.com/japan20.jpg', 'Had an amazing time visiting the beautiful island of Okinawa. A tropical paradise! #Okinawa #JapanIslands'),
(409, 'https://example.com/japan21.jpg', 'Visiting the famous Tsukiji Fish Market in Tokyo. The freshest seafood! #Tokyo #TsukijiMarket'),
(255, 'https://example.com/japan22.jpg', 'Enjoying the peaceful vibe in Arashiyama Bamboo Grove. Kyoto is so tranquil. #Kyoto #BambooGrove'),
(255, 'https://example.com/japan23.jpg', 'Exploring the ancient ruins of Himeji Castle. History and beauty in one place. #HimejiCastle #JapanHistory'),
(255, 'https://example.com/japan24.jpg', 'Taking a scenic walk along the Philosopher’s Path in Kyoto. The cherry blossoms are perfect! #Kyoto #PhilosophersPath'),
(255, 'https://example.com/japan25.jpg', 'Had an unforgettable time at a sumo match in Tokyo. Such an exciting experience! #Sumo #TokyoCulture'),
(409, 'https://example.com/japan26.jpg', 'Visited the Odaiba district in Tokyo. The views of the Rainbow Bridge were incredible! #Tokyo #Odaiba'),
(226, 'https://example.com/japan27.jpg', 'Spent the day exploring the iconic Shinto shrines of Nikko. A true cultural experience. #Nikko #ShintoShrines'),
(232, 'https://example.com/japan28.jpg', 'Hiking in the scenic Mount Takao near Tokyo. Stunning nature just outside the city. #MountTakao #JapanNature'),
(409, 'https://example.com/japan29.jpg', 'Taking in the breathtaking views of the Japanese countryside on the way to Nagano. #Nagano #JapanCountryside'),
(411, 'https://example.com/japan30.jpg', 'Visited the vibrant Dotonbori district in Osaka. The neon lights are amazing! #Dotonbori #OsakaNightlife'),
(410, 'https://example.com/japan31.jpg', 'Exploring the amazing shrines and gardens of Kyoto. This city is full of culture and history. #Kyoto #JapanTour'),
(412, 'https://example.com/japan32.jpg', 'Had a beautiful afternoon in the Gion district of Kyoto. The traditional teahouses are stunning! #Kyoto #GionDistrict'),
(411, 'https://example.com/japan33.jpg', 'Took a peaceful stroll through the gardens of the Imperial Palace in Tokyo. #Tokyo #ImperialPalaceGardens'),
(325, 'https://example.com/japan34.jpg', 'Spent the day wandering around the vibrant city of Sapporo. What a hidden gem in Hokkaido! #Sapporo #JapanTravel'),
(226, 'https://example.com/japan35.jpg', 'Had the best ramen of my life in Fukuoka. Ramen capital of Japan! #Fukuoka #RamenLover'),
(413, 'https://example.com/japan36.jpg', 'Visiting the historic Nijo Castle in Kyoto. Such an incredible place! #NijoCastle #KyotoHistory'),
(414, 'https://example.com/japan37.jpg', 'Hiking up Mount Fuji at sunrise was an unforgettable experience. Worth every step! #MountFuji #JapanAdventure'),
(415, 'https://example.com/japan38.jpg', 'Exploring the beautiful gardens of Shinjuku Gyoen National Garden in Tokyo. A peaceful escape. #Tokyo #ShinjukuGyoen'),
(150, 'https://example.com/japan39.jpg', 'Relaxing at the tranquil gardens of Kenrokuen in Kanazawa. #Kenrokuen #Kanazawa #JapanNature'),
(415, 'https://example.com/japan40.jpg', 'Spent an amazing day at the Tokyo Disneyland. So much fun! #TokyoDisneyland #FamilyFun'),
(409, 'https://example.com/japan41.jpg', 'Walked through the serene Meiji Shrine in Tokyo. It’s so peaceful. #MeijiShrine #TokyoShrines'),
(409, 'https://example.com/japan42.jpg', 'Taking a stroll through the historic district of Kanazawa. The architecture is beautiful! #Kanazawa #JapanHeritage'),
(408, 'https://example.com/japan43.jpg', 'Spent the day exploring the peaceful temple of Tōdai-ji in Nara. #TodaiJi #NaraTemples'),
(407, 'https://example.com/japan44.jpg', 'Exploring the beautiful streets of Kamakura and its famous Great Buddha statue. #Kamakura #GreatBuddha'),
(406, 'https://example.com/japan45.jpg', 'Had the best sushi dinner in Ginza, Tokyo. Can’t get any fresher than this! #Tokyo #SushiDinner'),
(409, 'https://example.com/japan46.jpg', 'Enjoying the beautiful views from the top of Tokyo Tower. #TokyoTower #JapanViews'),
(404, 'https://example.com/japan47.jpg', 'Visited the stunning Lake Kawaguchi with Mount Fuji in the background. Unforgettable! #LakeKawaguchi #MountFuji'),
(226, 'https://example.com/japan48.jpg', 'Admiring the beautiful autumn colors at the temples of Kyoto. #Kyoto #AutumnInJapan'),
(410, 'https://example.com/japan49.jpg', 'Had a fun time at Universal Studios Japan in Osaka. The rides were amazing! #UniversalStudios #OsakaAdventure'),
(412, 'https://example.com/japan50.jpg', 'Taking in the incredible views from the top of the Skytree in Tokyo. #TokyoSkytree #TokyoViews');

INSERT INTO posts (user_id, image_url, caption) VALUES
(121, 'https://example.com/california1.jpg', 'Exploring the beautiful beaches of Malibu. The sunsets here are stunning! #Malibu #CaliforniaBeaches'),
(145, 'https://example.com/california2.jpg', 'Had a fantastic hike up to the top of Mount Whitney. The views are breathtaking! #MountWhitney #CaliforniaAdventure'),
(118, 'https://example.com/california3.jpg', 'Enjoying the incredible food scene in San Francisco. So many amazing restaurants! #SanFrancisco #FoodieLife'),
(150, 'https://example.com/california4.jpg', 'Visiting the iconic Golden Gate Bridge in San Francisco. What a sight! #GoldenGateBridge #SF #California'),
(123, 'https://example.com/california5.jpg', 'Spent the day at Yosemite National Park. The waterfalls are magnificent! #Yosemite #CaliforniaNature'),
(156, 'https://example.com/california6.jpg', 'Taking a scenic drive along the Pacific Coast Highway. The ocean views are unbeatable! #PCH #CaliforniaCoast'),
(130, 'https://example.com/california7.jpg', 'Exploring the vibrant streets of Los Angeles. So much to see and do! #LosAngeles #CaliforniaCityLife'),
(130, 'https://example.com/california8.jpg', 'Visited the beautiful Lake Tahoe today. So peaceful and relaxing! #LakeTahoe #CaliforniaMountains'),
(150, 'https://example.com/california9.jpg', 'Had an amazing time at Disneyland. It’s like stepping into a magical world! #Disneyland #CaliforniaDreaming'),
(120, 'https://example.com/california10.jpg', 'Walking through the stunning vineyards in Napa Valley. The wine here is top-notch! #NapaValley #CaliforniaWine'),
(119, 'https://example.com/california11.jpg', 'Took a walk through the iconic Venice Beach Boardwalk. Such a fun atmosphere! #VeniceBeach #LosAngeles'),
(130, 'https://example.com/california12.jpg', 'Spent the day in San Diego. The zoo and the beaches are a must-see! #SanDiego #CaliforniaFun'),
(130, 'https://example.com/california13.jpg', 'Visiting the amazing Sequoia National Park. These trees are beyond massive! #SequoiaNationalPark #CaliforniaNature'),
(145, 'https://example.com/california14.jpg', 'Taking in the stunning views from the Griffith Observatory in Los Angeles. #GriffithObservatory #LACityViews'),
(130, 'https://example.com/california15.jpg', 'Strolling through the famous streets of Santa Monica. What a lively place! #SantaMonica #CaliforniaVibes'),
(140, 'https://example.com/california16.jpg', 'Exploring the gorgeous beaches of Big Sur. The cliffs and ocean views are incredible! #BigSur #CaliforniaCoast'),
(117, 'https://example.com/california17.jpg', 'Visited the stunning Death Valley National Park. It’s one of the hottest places on earth! #DeathValley #CaliforniaDesert'),
(120, 'https://example.com/california18.jpg', 'Had an unforgettable time at the California Academy of Sciences in San Francisco. #CaliforniaAcademyOfSciences #SanFrancisco'),
(150, 'https://example.com/california19.jpg', 'Exploring the beautiful Muir Woods National Monument. The towering redwoods are amazing! #MuirWoods #Redwoods'),
(140, 'https://example.com/california20.jpg', 'Enjoyed a peaceful day at the stunning Mono Lake. The landscape here is unique! #MonoLake #CaliforniaNature'),
(150, 'https://example.com/california21.jpg', 'Visited the incredible Hearst Castle today. The architecture is stunning! #HearstCastle #CaliforniaHistory'),
(150, 'https://example.com/california22.jpg', 'Had an amazing time at Universal Studios Hollywood. The rides were incredible! #UniversalStudios #HollywoodFun'),
(160, 'https://example.com/california23.jpg', 'Hiking in the stunning Joshua Tree National Park. The desert landscape is so beautiful! #JoshuaTree #CaliforniaHiking'),
(150, 'https://example.com/california24.jpg', 'Took a trip to the charming town of Carmel-by-the-Sea. Such a picturesque place! #CarmelByTheSea #CaliforniaGetaway'),
(140, 'https://example.com/california25.jpg', 'Exploring the iconic Hollywood Walk of Fame. A must-see when in LA! #HollywoodWalkOfFame #LosAngeles'),
(132, 'https://example.com/california26.jpg', 'Spent the day at the famous Santa Barbara Mission. Such a beautiful and historic site! #SantaBarbara #CaliforniaHistory'),
(132, 'https://example.com/california27.jpg', 'Took a boat tour around Catalina Island. The island views were incredible! #CatalinaIsland #CaliforniaCoast'),
(132, 'https://example.com/california28.jpg', 'Explored the unique landscape of Lassen Volcanic National Park. So much to see! #LassenVolcanicPark #CaliforniaNature'),
(132, 'https://example.com/california29.jpg', 'Visited the peaceful Japanese Garden in San Diego. So serene and beautiful. #JapaneseGarden #SanDiego'),
(117, 'https://example.com/california30.jpg', 'Had an unforgettable time at the San Francisco Museum of Modern Art. A true cultural gem! #SFMOMA #SanFranciscoArt'),
(1368, 'https://example.com/california31.jpg', 'Relaxing on the stunning beaches of Santa Cruz. The surf is perfect here! #SantaCruz #CaliforniaBeaches'),
(1368, 'https://example.com/california32.jpg', 'Spent the day in the picturesque town of Sausalito. Such a peaceful and charming place. #Sausalito #SanFranciscoBay'),
(1370, 'https://example.com/california33.jpg', 'Exploring the colorful streets of Old Town San Diego. So full of history and culture! #OldTownSanDiego #CaliforniaHistory'),
(1360, 'https://example.com/california34.jpg', 'Took a scenic walk through Golden Gate Park in San Francisco. Beautiful! #GoldenGatePark #SanFrancisco'),
(1366, 'https://example.com/california35.jpg', 'Visited the amazing Lake Arrowhead. It’s so peaceful up here! #LakeArrowhead #CaliforniaMountains'),
(1365, 'https://example.com/california36.jpg', 'Had the most delicious fish tacos in Santa Barbara. #SantaBarbara #FishTacos #CaliforniaEats'),
(226, 'https://example.com/california37.jpg', 'Exploring the colorful murals of Balmy Alley in San Francisco. Such vibrant art! #BalmyAlley #SanFranciscoArt'),
(1365, 'https://example.com/california38.jpg', 'Spent the afternoon at the Getty Center in Los Angeles. The views and art are amazing! #GettyCenter #LosAngelesCulture'),
(150, 'https://example.com/california39.jpg', 'Hiking to the top of the Torrey Pines State Reserve. The views were worth it! #TorreyPines #SanDiegoHiking'),
(1359, 'https://example.com/california40.jpg', 'Had an unforgettable experience at the California State Fair in Sacramento. #CaliforniaStateFair #SacramentoFun'),
(1358, 'https://example.com/california41.jpg', 'Relaxing at the beautiful Point Reyes National Seashore. Such a tranquil spot. #PointReyes #CaliforniaNature'),
(1364, 'https://example.com/california42.jpg', 'Spent the weekend exploring the charming town of Mendocino. #Mendocino #CaliforniaGetaway'),
(1366, 'https://example.com/california43.jpg', 'Exploring the beautiful beaches of Pismo Beach. #PismoBeach #CaliforniaCoast'),
(1367, 'https://example.com/california44.jpg', 'Visited the gorgeous Death Valley National Park. The desert landscapes are unreal. #DeathValley #CaliforniaDesert'),
(1368, 'https://example.com/california45.jpg', 'Enjoying the amazing views of Big Bear Lake. Perfect for a peaceful retreat. #BigBearLake #CaliforniaMountains'),
(1189, 'https://example.com/california46.jpg', 'Spent the day in the beautiful city of Pasadena. Such a historic and charming place. #Pasadena #CaliforniaCity'),
(1345, 'https://example.com/california47.jpg', 'Took a relaxing boat ride on the Napa River. #NapaValley #CaliforniaWine'),
(1456, 'https://example.com/california48.jpg', 'Exploring the beautiful Mission San Juan Capistrano. Such a historic gem! #MissionSanJuanCapistrano #CaliforniaHistory'),
(1450, 'https://example.com/california49.jpg', 'Had an unforgettable experience at the California Science Center in LA. #CaliforniaScienceCenter #LosAngeles'),
(1453, 'https://example.com/california50.jpg', 'Spent the day in the vibrant town of Laguna Beach. The art scene here is amazing! #LagunaBeach #CaliforniaArts');

INSERT INTO posts (user_id, image_url, caption) VALUES
(226, 'https://example.com/hawaii1.jpg', 'Exploring the volcanic landscapes of Hawaii Volcanoes National Park. Incredible experience! #HawaiiVolcanoes #BigIsland'),
(226, 'https://example.com/hawaii2.jpg', 'Had the most relaxing time at Waikiki Beach. Perfect spot to unwind. #WaikikiBeach #Oahu'),
(226, 'https://example.com/hawaii3.jpg', 'Trekking through the lush trails of Kauai. Nature here is just breathtaking! #Kauai #HawaiiAdventure'),
(226, 'https://example.com/hawaii4.jpg', 'Sunset at Hanauma Bay is an absolute must. The colors are unreal! #HanaumaBay #OahuSunset'),
(226, 'https://example.com/hawaii5.jpg', 'Enjoyed a scenic helicopter ride over the Na Pali Coast. Views that you’ll never forget! #NaPaliCoast #KauaiHelicopterTour'),
(325, 'https://example.com/hawaii6.jpg', 'Spent the day exploring Pearl Harbor. A truly humbling experience. #PearlHarbor #OahuHistory'),
(226, 'https://example.com/hawaii7.jpg', 'Visiting the beaches of Maui. The sands are perfect, and the waves are incredible for surfing! #MauiBeaches #HawaiiSurfing'),
(226, 'https://example.com/hawaii8.jpg', 'Hiking the famous Diamond Head Trail. The view from the top of Oahu is incredible! #DiamondHead #OahuHikes'),
(100, 'https://example.com/hawaii9.jpg', 'Snorkeling in the crystal-clear waters of Molokini Crater. What an unforgettable experience! #MolokiniCrater #HawaiiSnorkeling'),
(100, 'https://example.com/hawaii10.jpg', 'Enjoying the serene beauty of Waimea Canyon. Often called the Grand Canyon of the Pacific! #WaimeaCanyon #Kauai'),
(226, 'https://example.com/hawaii11.jpg', 'Watching the surfers at Sunset Beach. Such an iconic spot on the North Shore! #SunsetBeach #NorthShoreOahu'),
(325, 'https://example.com/hawaii12.jpg', 'Hiking through the bamboo forest in Hana. The jungle vibes are surreal! #HanaBambooForest #MauiHikes'),
(100, 'https://example.com/hawaii13.jpg', 'Exploring the unique black sand beaches of Punaluu. An incredible sight! #PunaluuBeach #BigIsland'),
(244, 'https://example.com/hawaii14.jpg', 'Sunrise at Haleakalā National Park. Watching the sun rise from the top of the world! #HaleakalaSunrise #MauiViews'),
(244, 'https://example.com/hawaii15.jpg', 'Spent the day at the beautiful Lanikai Beach. Pure paradise! #LanikaiBeach #Oahu'),
(244, 'https://example.com/hawaii16.jpg', 'The road to Hana is full of stunning views and waterfalls. Definitely worth the drive! #RoadToHana #MauiAdventure'),
(246, 'https://example.com/hawaii17.jpg', 'Chillin’ on the beaches of Lanai. Secluded and peaceful. #LanaiBeaches #HawaiiGetaway'),
(246, 'https://example.com/hawaii18.jpg', 'Explored the lush and tropical Kualoa Ranch. So much history and beauty! #KualoaRanch #Oahu'),
(247, 'https://example.com/hawaii19.jpg', 'Had an amazing time whale watching in Maui. These creatures are so majestic! #MauiWhaleWatching #HawaiiNature'),
(248, 'https://example.com/hawaii20.jpg', 'Taking in the spectacular sunset at Kailua Beach. Hawaii’s sunsets are like no other. #KailuaBeach #HawaiiSunsets'),
(248, 'https://example.com/hawaii21.jpg', 'Explored the botanical gardens in Hilo. Such a peaceful place to connect with nature. #HiloBotanicalGarden #BigIslandNature'),
(250, 'https://example.com/hawaii22.jpg', 'Had a blast hiking through the lush jungle of the Hana rainforest. #HanaRainforest #MauiHikes'),
(250, 'https://example.com/hawaii23.jpg', 'The view from the top of the Makapu’u Lighthouse Trail is worth the hike. #Makapu’uLighthouse #OahuHikes'),
(250, 'https://example.com/hawaii24.jpg', 'Enjoying a scenic boat ride along the Na Pali Coast. One of the most beautiful spots in Hawaii! #NaPaliCoastBoatRide #Kauai'),
(250, 'https://example.com/hawaii25.jpg', 'Visiting the stunning Napali Coast by boat. The cliffs are absolutely dramatic! #NapaliCoast #KauaiBoatTour'),
(251, 'https://example.com/hawaii26.jpg', 'Waking up to the sound of the ocean at Hanalei Bay. What a way to start the day! #HanaleiBay #Kauai'),
(253, 'https://example.com/hawaii27.jpg', 'Just finished an amazing snorkeling session at Kailua Bay. The underwater world is so vibrant! #KailuaBay #HawaiiSnorkeling'),
(253, 'https://example.com/hawaii28.jpg', 'Exploring the majestic Akaka Falls on the Big Island. So beautiful! #AkakaFalls #BigIslandWaterfalls'),
(253, 'https://example.com/hawaii29.jpg', 'Had an unforgettable time kayaking in Kailua. Such an idyllic place to paddle! #KailuaKayaking #Oahu'),
(254, 'https://example.com/hawaii30.jpg', 'Visiting the Iolani Palace in Honolulu. Hawaii’s royal history is fascinating. #IolaniPalace #OahuHistory'),
(254, 'https://example.com/hawaii31.jpg', 'Went on a sunset boat ride in Waikiki. The views of the city are magical. #WaikikiSunset #OahuBoatTour'),
(255, 'https://example.com/hawaii32.jpg', 'Taking a walk around the beautiful Lahaina town. So much history and culture! #Lahaina #MauiHistory'),
(255, 'https://example.com/hawaii33.jpg', 'Hiked to the top of the Makena State Park. The views of the coastline are breathtaking! #MakenaStatePark #MauiHikes'),
(256, 'https://example.com/hawaii34.jpg', 'Visited the Hana Lava Tube. Such a fascinating underground adventure! #HanaLavaTube #MauiAdventure'),
(257, 'https://example.com/hawaii35.jpg', 'Enjoying the tropical gardens at the Hawaii Tropical Botanical Garden in Hilo. #HawaiiTropicalGarden #BigIsland'),
(257, 'https://example.com/hawaii36.jpg', 'Took a dip in the refreshing waters of Waimea Bay. A perfect day on the beach. #WaimeaBay #OahuBeaches'),
(258, 'https://example.com/hawaii37.jpg', 'Exploring the unique landscapes of the Kalalau Trail. Definitely a hike to remember! #KalalauTrail #KauaiHiking'),
(259, 'https://example.com/hawaii38.jpg', 'Enjoying the fresh air and stunning views from the Waimea Canyon. #WaimeaCanyon #KauaiViews'),
(259, 'https://example.com/hawaii39.jpg', 'Having a blast surfing at Pipeline Beach in Oahu. This is the place for big waves! #PipelineBeach #OahuSurfing'),
(260, 'https://example.com/hawaii40.jpg', 'Went for a peaceful paddleboard session at Ala Moana Beach Park. #AlaMoanaBeach #Honolulu'),
(260, 'https://example.com/hawaii41.jpg', 'Just finished an amazing dive at the wreck of the USS Liberty in Hawaii. So much history underwater! #USSLibertyWreck #HawaiiDiving'),
(244, 'https://example.com/hawaii42.jpg', 'Enjoyed a magical sunset boat ride along the coast of Maui. Such a serene experience! #MauiSunset #HawaiiCoast'),
(226, 'https://example.com/hawaii43.jpg', 'Taking in the view from the top of the scenic Pali Lookout. A must-see in Oahu! #PaliLookout #OahuViews'),
(246, 'https://example.com/hawaii44.jpg', 'Had a great time at the Ala Moana Center shopping in Honolulu. What a vibrant mall! #AlaMoanaCenter #OahuShopping'),
(325, 'https://example.com/hawaii45.jpg', 'Took a relaxing stroll through the beautiful Koko Crater Botanical Garden. #KokoCraterBotanicalGarden #OahuNature'),
(326, 'https://example.com/hawaii46.jpg', 'Visited the Hana Cultural Center. So much history and culture in this beautiful town. #HanaCulturalCenter #MauiHistory'),
(326, 'https://example.com/hawaii47.jpg', 'Tried traditional Hawaiian food at a local luau. The flavors are incredible! #HawaiianLuau #HawaiiEats'),
(326, 'https://example.com/hawaii48.jpg', 'Made my way to the top of the Diamond Head Crater Trail. A challenging hike, but the view is worth it! #DiamondHeadTrail #OahuHikes'),
(253, 'https://example.com/hawaii49.jpg', 'Spent the day in the botanical gardens at the National Tropical Botanical Garden. #NationalTropicalBotanicalGarden #Kauai'),
(252, 'https://example.com/hawaii50.jpg', 'Exploring the beautiful Makapu’u Beach in Oahu. The water is so blue! #Makapu’uBeach #OahuNature');

INSERT INTO posts (user_id, image_url, caption) VALUES
(845, 'https://example.com/sf1.jpg', 'Waking up to a foggy morning in San Francisco. The Golden Gate Bridge never gets old. #GoldenGateBridge #SFViews'),
(858, 'https://example.com/sf2.jpg', 'Enjoying the beautiful streets of Sausalito. Just a short ferry ride from SF but feels like a world away. #Sausalito #BayAreaLiving'),
(800, 'https://example.com/sf3.jpg', 'Spending the weekend in Marin County. The views from Mt. Tamalpais are breathtaking! #MarinCounty #BayAreaHikes'),
(820, 'https://example.com/sf4.jpg', 'Exploring the iconic Fishermans Wharf. The seafood here is always fresh! #FishermansWharf #SanFranciscoEats'),
(800, 'https://example.com/sf5.jpg', 'Took a stroll through Golden Gate Park today. There’s so much to explore, from gardens to museums. #GoldenGatePark #SFOutdoors'),
(850, 'https://example.com/sf6.jpg', 'Sundays are for brunch at Dolores Park! Perfect view of the city and the weather is always beautiful. #DoloresPark #SFBayAreaLife'),
(850, 'https://example.com/sf7.jpg', 'Hiking the Presidio and seeing the Golden Gate from a new perspective. So much to explore here! #PresidioHikes #GoldenGateViews'),
(800, 'https://example.com/sf8.jpg', 'Weekend trip to Napa Valley. It’s not just the wine – the views are incredible too. #NapaValley #CaliforniaWineCountry'),
(850, 'https://example.com/sf9.jpg', 'Driving through the Bay Area’s iconic fog. SF mornings are magical! #SFBayArea #FoggyMornings'),
(800, 'https://example.com/sf10.jpg', 'Made it to the top of Twin Peaks! The panoramic views of the city are worth every step. #TwinPeaks #SanFranciscoViews'),
(850, 'https://example.com/sf11.jpg', 'Exploring the vibrant Mission District. Street art, food, and culture make this place so unique. #MissionDistrict #SFExploring'),
(800, 'https://example.com/sf12.jpg', 'Having an afternoon coffee in the Ferry Building. The view of the Bay Bridge is unbeatable! #FerryBuilding #SFViews'),
(850, 'https://example.com/sf13.jpg', 'Enjoying the sunset at Baker Beach. A perfect way to end the day with a view of the Golden Gate Bridge. #BakerBeach #SFSunsets'),
(800, 'https://example.com/sf14.jpg', 'Taking a ferry ride to Angel Island today. A beautiful escape from the city! #AngelIsland #BayAreaGetaway'),
(850, 'https://example.com/sf15.jpg', 'Can’t get enough of the Bay Area’s food scene. Brunch at Tartine Bakery never disappoints! #TartineBakery #SanFranciscoEats'),
(800, 'https://example.com/sf16.jpg', 'Just visited the California Academy of Sciences. It’s a must-see for anyone in SF! #CaliforniaAcademyOfSciences #SFAttractions'),
(850, 'https://example.com/sf17.jpg', 'Took a walk across the Golden Gate Bridge today. It never ceases to amaze me! #GoldenGateBridge #SFViews'),
(833, 'https://example.com/sf18.jpg', 'Checking out the amazing murals in the Mission District. The art scene here is next-level. #MissionMurals #SFStreetArt'),
(850, 'https://example.com/sf19.jpg', 'Visited Alcatraz Island today. The history here is so fascinating! #AlcatrazIsland #SFHistory'),
(844, 'https://example.com/sf20.jpg', 'Had an incredible day hiking in Marin Headlands. The views of the Bay Area are unparalleled. #MarinHeadlands #BayAreaHiking'),
(854, 'https://example.com/sf21.jpg', 'Weekend getaway to Santa Cruz. The beaches are perfect for surfing and relaxing. #SantaCruz #BayAreaGetaways'),
(835, 'https://example.com/sf22.jpg', 'The Golden Gate Park is such an oasis in the middle of the city. It’s my favorite place for a walk. #GoldenGatePark #SFOutdoors'),
(842, 'https://example.com/sf23.jpg', 'Spending the day in Napa. Wine tastings and beautiful vineyards make this place so relaxing. #NapaVineyards #WineCountry'),
(852, 'https://example.com/sf24.jpg', 'The views from the Marin Headlands are just incredible. San Francisco looks stunning from across the Bay! #MarinHeadlands #SFViews'),
(845, 'https://example.com/sf25.jpg', 'Caught a beautiful sunset from Crissy Field. Can’t get enough of this place! #CrissyField #SanFranciscoSunsets'),
(850, 'https://example.com/sf26.jpg', 'Explored the quaint town of Sausalito today. The views of the city skyline are beautiful! #Sausalito #SFViews'),
(855, 'https://example.com/sf27.jpg', 'Took a day trip to Muir Woods National Monument. It’s so peaceful here among the giant redwoods. #MuirWoods #Redwoods'),
(864, 'https://example.com/sf28.jpg', 'Exploring downtown SF today. The architecture and culture are incredible! #SanFranciscoDowntown #CityLife'),
(863, 'https://example.com/sf29.jpg', 'Had an amazing day hiking in Point Reyes National Seashore. Perfect views of the ocean and cliffs. #PointReyes #NatureEscape'),
(850, 'https://example.com/sf30.jpg', 'Visited the iconic Painted Ladies today. These historic Victorian houses are so charming! #PaintedLadies #SFLandmarks'),
(842, 'https://example.com/sf31.jpg', 'Strolling through the Presidio and enjoying the serene views of the Golden Gate Bridge. #PresidioSF #GoldenGateBridgeViews'),
(849, 'https://example.com/sf32.jpg', 'Spent the weekend exploring the stunning Redwood National and State Parks. The trees here are so majestic! #RedwoodNationalPark #NorthernCalifornia'),
(847, 'https://example.com/sf33.jpg', 'Had a great time at the San Francisco Museum of Modern Art. There’s so much to see here! #SFMOMA #ArtLover'),
(857, 'https://example.com/sf34.jpg', 'Driving down Highway 1 along the coast of California. The views of the ocean are breathtaking! #Highway1 #CaliforniaCoast'),
(858, 'https://example.com/sf35.jpg', 'Visited the Exploratorium in SF today. It’s such a fun and interactive museum! #Exploratorium #SFAttractions'),
(843, 'https://example.com/sf36.jpg', 'Explored the Japanese Tea Garden in Golden Gate Park. It’s so peaceful and beautiful here. #JapaneseTeaGarden #GoldenGatePark'),
(852, 'https://example.com/sf37.jpg', 'A day spent kayaking on the Bay with views of the Golden Gate Bridge is just perfect! #KayakingSF #GoldenGateBridgeViews'),
(811, 'https://example.com/sf38.jpg', 'Had an amazing time at the Ferry Building Marketplace. The food is incredible here! #FerryBuilding #SFEats'),
(831, 'https://example.com/sf39.jpg', 'Woke up early to catch the sunrise at Twin Peaks. SF looks magical in the early morning light. #TwinPeaks #SunriseViews'),
(833, 'https://example.com/sf40.jpg', 'Enjoyed a peaceful day at Stinson Beach. Such a relaxing spot on the coast. #StinsonBeach #BayAreaBeaches'),
(825, 'https://example.com/sf41.jpg', 'Visiting the de Young Museum today. Always something new to see! #deYoungMuseum #SFArt'),
(832, 'https://example.com/sf42.jpg', 'Had the best time at the San Francisco Giants game at Oracle Park. The views from the stadium are incredible! #OraclePark #SFGiants'),
(804, 'https://example.com/sf43.jpg', 'A perfect day spent at the Bay Area Discovery Museum in Sausalito. Perfect for families! #BayAreaDiscoveryMuseum #Sausalito'),
(810, 'https://example.com/sf44.jpg', 'Enjoying the view of the city skyline from Coit Tower. The 360-degree view is amazing! #CoitTower #SFViews'),
(835, 'https://example.com/sf45.jpg', 'Took a scenic walk along the Embarcadero. The views of the Bay Bridge are stunning! #Embarcadero #SFOceanViews'),
(842, 'https://example.com/sf46.jpg', 'Had a wonderful time at the San Francisco Botanical Garden. Such a peaceful place to explore. #SFBotanicalGarden #SFOutdoors'),
(841, 'https://example.com/sf47.jpg', 'Visited the California Palace of the Legion of Honor. The art collections here are amazing! #LegionOfHonor #SFMuseums'),
(836, 'https://example.com/sf48.jpg', 'Took a ferry ride to Angel Island today. So much history and amazing views! #AngelIsland #SFHistory'),
(862, 'https://example.com/sf49.jpg', 'Enjoying a peaceful evening walk through the Bay Area’s amazing parks. #SFOutdoors #BayAreaParks'),
(862, 'https://example.com/sf50.jpg', 'Spending the afternoon at the Golden Gate Bridge Visitor Center. It’s great to learn more about the bridge’s history. #GoldenGateVisitorCenter #SanFranciscoLandmarks');

INSERT INTO posts (user_id, image_url, caption) VALUES
(801, 'https://example.com/sf_startup1.jpg', 'Excited to start my journey in a tech startup in the heart of the Bay Area! The possibilities are endless. #TechStartup #BayAreaLife'),
(811, 'https://example.com/sf_startup2.jpg', 'First day at the new startup office. The energy here is contagious! #FirstDay #StartupLife'),
(811, 'https://example.com/sf_startup3.jpg', 'The startup culture in SF is incredible. From free coffee to brainstorming sessions, I’m loving it! #StartupCulture #BayAreaTech'),
(832, 'https://example.com/sf_startup4.jpg', 'Working in a tech startup means constant learning. Every day brings new challenges and opportunities. #LearningEveryDay #TechStartup'),
(850, 'https://example.com/sf_startup5.jpg', 'Spent the day at a networking event with other tech entrepreneurs. The energy in the Bay Area is unmatched! #Networking #TechEvents'),
(843, 'https://example.com/sf_startup6.jpg', 'Started my first project at the new tech startup. It’s challenging but so rewarding! #TechLife #StartupJourney'),
(863, 'https://example.com/sf_startup7.jpg', 'Taking a break at the rooftop terrace of our office. The views of the Bay Area are amazing! #TechStartupViews #BayAreaViews'),
(841, 'https://example.com/sf_startup8.jpg', 'It’s crazy to think I’m now part of a startup that’s shaping the future of tech! Feeling so inspired. #TechInnovation #SFStartup'),
(851, 'https://example.com/sf_startup9.jpg', 'Every day at the startup brings a new learning experience. Couldn’t have asked for a better start to my tech career. #TechCareer #StartupGrowth'),
(226, 'https://example.com/sf_startup10.jpg', 'Visited a coworking space in San Francisco today. The startup ecosystem here is thriving! #Coworking #BayAreaTech'),
(844, 'https://example.com/sf_startup11.jpg', 'Celebrating the small wins at our tech startup. It’s all about the hustle here! #StartUpWins #TechStartupLife'),
(854, 'https://example.com/sf_startup12.jpg', 'Just wrapped up a strategy session at work. Collaborating with such brilliant minds is a huge privilege. #Teamwork #TechLeadership'),
(855, 'https://example.com/sf_startup13.jpg', 'Tech startup life isn’t easy, but it’s definitely exciting! Looking forward to seeing what the future holds. #StartupGrind #BayAreaTech'),
(854, 'https://example.com/sf_startup14.jpg', 'Got my first promotion at the startup! Hard work and innovation are paying off. #StartupSuccess #TechCareer'),
(849, 'https://example.com/sf_startup15.jpg', 'Tech startups in SF are the place to be for ambitious professionals. So many opportunities for growth here. #SFStartupScene #TechOpportunities'),
(819, 'https://example.com/sf_startup16.jpg', 'Exploring the startup hubs in SF today. Everywhere you look, there’s innovation happening. #InnovationInSF #TechStartup'),
(810, 'https://example.com/sf_startup17.jpg', 'Day one at the tech startup. I can already feel the adrenaline of working in such a fast-paced environment. #StartupVibes #SFTech'),
(810, 'https://example.com/sf_startup18.jpg', 'Love the flexible work culture at my startup. It’s amazing to work in a place that promotes creativity and freedom. #WorkCulture #TechStartup'),
(811, 'https://example.com/sf_startup19.jpg', 'The startup life is all about constant problem-solving. And I’m here for it! #TechProblems #StartupLife'),
(811, 'https://example.com/sf_startup20.jpg', 'Started the week with an exciting product launch at work. The team here is incredible! #ProductLaunch #StartupTeam'),
(812, 'https://example.com/sf_startup21.jpg', 'Living in SF and working at a tech startup is everything I dreamed of and more. #SFLife #TechLife'),
(813, 'https://example.com/sf_startup22.jpg', 'Excited for a team-building day at work! It’s great to have colleagues who push you to do your best. #TeamBuilding #SFStartup'),
(814, 'https://example.com/sf_startup23.jpg', 'Got my first project proposal approved at work! Feels great to contribute to something so meaningful. #TechProjects #StartupSuccess'),
(815, 'https://example.com/sf_startup24.jpg', 'The startup life can be intense, but it’s the best place to grow your skills. #StartUpJourney #TechCareer'),
(816, 'https://example.com/sf_startup25.jpg', 'Just completed my first week at the startup. So many new ideas and things to learn! #TechInnovation #BayAreaStartups'),
(817, 'https://example.com/sf_startup26.jpg', 'Spending the day at the office, brainstorming ideas with the team. There’s always something exciting going on here. #TeamWork #BayAreaTech'),
(818, 'https://example.com/sf_startup27.jpg', 'Feeling inspired after an amazing week of growth at the startup. Ready to tackle the next challenge! #StartupGrowth #TechVibes'),
(819, 'https://example.com/sf_startup28.jpg', 'Visited a local tech incubator today. It’s amazing to see so many startups in one place! #TechIncubator #SFStartups'),
(820, 'https://example.com/sf_startup29.jpg', 'Just moved into my new office at the startup. Can’t wait to start building something great here! #TechOffice #StartUpLife'),
(820, 'https://example.com/sf_startup30.jpg', 'Celebrating our startup’s first big milestone today. The future looks bright! #StartUpMilestone #TechSuccess'),
(855, 'https://example.com/sf_startup31.jpg', 'Loving the flexibility to work from home sometimes. It’s one of the perks of working in a tech startup. #WorkFromHome #TechStartup'),
(859, 'https://example.com/sf_startup32.jpg', 'Met some amazing people at a startup conference today. Networking in SF is such a great experience. #StartupConference #TechNetworking'),
(812, 'https://example.com/sf_startup33.jpg', 'Tech startups in the Bay Area are always moving fast. It’s exciting to be part of such a vibrant community. #BayAreaTech #StartupEnergy'),
(816, 'https://example.com/sf_startup34.jpg', 'Just finished a brainstorming session. Feeling so motivated to contribute more to this growing tech startup. #BrainstormingSession #TechVibes'),
(813, 'https://example.com/sf_startup35.jpg', 'Taking a break from work to check out the view from our startup’s office. SF never looked so good! #OfficeViews #BayAreaTech'),
(817, 'https://example.com/sf_startup36.jpg', 'Every day feels like a new adventure in the startup world. Can’t wait to see where this journey takes me. #TechStartupJourney #Innovation'),
(814, 'https://example.com/sf_startup37.jpg', 'The best part of working at a startup is the opportunity to make a real impact. #StartupImpact #TechCareers'),
(819, 'https://example.com/sf_startup38.jpg', 'Hitting new milestones in our product development today. It’s amazing to be part of such a talented team. #ProductDevelopment #TechTeam'),
(866, 'https://example.com/sf_startup39.jpg', 'The pace at a tech startup is fast, but that’s what keeps it exciting. Can’t wait for what’s next. #FastPacedWork #TechLife'),
(810, 'https://example.com/sf_startup40.jpg', 'Team lunches and brainstorms make working at a startup so much fun. #StartupCulture #TechTeam'),
(827, 'https://example.com/sf_startup41.jpg', 'Just got my first tech project off the ground. The startup life is all about turning ideas into reality. #TechProjects #StartupLife'),
(816, 'https://example.com/sf_startup42.jpg', 'Grateful for the opportunities to learn and grow at my startup. #StartupGrowth #TechJourney'),
(818, 'https://example.com/sf_startup43.jpg', 'Got my hands on some cool new technology for a project. This is why I love working in tech! #TechInnovation #StartupProjects'),
(820, 'https://example.com/sf_startup44.jpg', 'Excited to work on new features at my startup. The team is so motivated! #TechFeatures #StartupVibes'),
(817, 'https://example.com/sf_startup45.jpg', 'Wrapping up an amazing week of progress at the tech startup. The future looks so bright! #StartupProgress #TechSuccess'),
(854, 'https://example.com/sf_startup46.jpg', 'The perks of working in a Bay Area startup – from free snacks to a great team! #TechPerks #StartupLife'),
(812, 'https://example.com/sf_startup47.jpg', 'Diving into the world of tech development. Loving every minute of it. #TechDevelopment #BayAreaStartups'),
(819, 'https://example.com/sf_startup48.jpg', 'Wrapping up a successful meeting with the team. Startups are all about collaboration and innovation. #TeamWork #TechStartup'),
(813, 'https://example.com/sf_startup49.jpg', 'Feeling thankful for my incredible colleagues. We’re building something amazing at the startup. #TechTeam #StartUpJourney'),
(820, 'https://example.com/sf_startup50.jpg', 'Another busy but exciting week at the startup. So proud of the progress we’ve made. #StartUpSuccess #TechJourney');

INSERT INTO posts (user_id, image_url, caption) VALUES
(901, 'https://example.com/sf_bigtech1.jpg', 'Excited to start my journey in a big tech company here in the Bay Area. Let’s get this started! #TechLife #BayAreaLiving'),
(901, 'https://example.com/sf_bigtech2.jpg', 'Enjoying the perks of working at a big tech company in SF. Free snacks and coffee all day long! #TechPerks #BayAreaLife'),
(902, 'https://example.com/sf_bigtech3.jpg', 'First day at the new tech company! The office is huge, and the energy is incredible. #BigTech #SFStartup'),
(902, 'https://example.com/sf_bigtech4.jpg', 'Had an amazing lunch break exploring the city. San Francisco has so much to offer! #LunchBreak #SFExploration'),
(893, 'https://example.com/sf_bigtech5.jpg', 'I’ve officially joined a big tech company in the heart of Silicon Valley. Couldn’t be more excited! #TechCompany #SiliconValley'),
(894, 'https://example.com/sf_bigtech6.jpg', 'The tech culture in the Bay Area is something else. So much collaboration and innovation happening daily. #TechCulture #Innovation'),
(895, 'https://example.com/sf_bigtech7.jpg', 'Celebrated my first milestone at the tech company today! Grateful for the opportunities to grow and learn. #CareerGoals #BigTech'),
(895, 'https://example.com/sf_bigtech8.jpg', 'Spending a weekend in San Francisco. The city is even more beautiful after working here all week. #SFWeekend #TechLife'),
(896, 'https://example.com/sf_bigtech9.jpg', 'Another day, another exciting project at work. The pace here is fast, but I’m loving every minute of it. #TechProjects #FastPacedLife'),
(887, 'https://example.com/sf_bigtech10.jpg', 'The big tech company I’m working at is focused on making a real difference in the world. Proud to be a part of it. #TechForGood #Innovation'),
(887, 'https://example.com/sf_bigtech11.jpg', 'Nothing like a walk around the office campus to clear my head and spark new ideas. #OfficeBreak #TechCampus'),
(888, 'https://example.com/sf_bigtech12.jpg', 'Had a team lunch at a local SF spot today. The food here is amazing, and the team culture is even better! #TeamLunch #TechCulture'),
(888, 'https://example.com/sf_bigtech13.jpg', 'First full week at the big tech company and I’m already learning so much. Can’t wait to see where this journey takes me. #CareerGrowth #TechJourney'),
(879, 'https://example.com/sf_bigtech14.jpg', 'Living in the Bay Area is everything I dreamed of. Excited for the next big project at work! #TechLife #BayAreaLiving'),
(879, 'https://example.com/sf_bigtech15.jpg', 'Work-life balance at a big tech company? Yes, please! Loving the flexibility here. #WorkLifeBalance #TechCompany'),
(890, 'https://example.com/sf_bigtech16.jpg', 'Spent the morning working from the office in San Francisco. Couldn’t ask for a better view while I work! #OfficeViews #SFTech'),
(890, 'https://example.com/sf_bigtech17.jpg', 'This is the life—working in a big tech company while living in one of the best cities in the world. #SFTech #WorkPerks'),
(891, 'https://example.com/sf_bigtech18.jpg', 'Inspiring conversations at work today. So proud to be part of this big tech company. #TechInspiration #BayAreaTech'),
(881, 'https://example.com/sf_bigtech19.jpg', 'The people at my tech company are amazing. Learning so much from my colleagues every day. #TechTeam #CareerGrowth'),
(882, 'https://example.com/sf_bigtech20.jpg', 'From the office to the city—loving every moment in San Francisco. #LifeInSF #TechCompany'),
(882, 'https://example.com/sf_bigtech21.jpg', 'Tech work in SF is fast-paced, but so rewarding. Ready to tackle another week of challenges! #TechChallenges #SFLiving'),
(893, 'https://example.com/sf_bigtech22.jpg', 'Today was all about brainstorming new ideas at work. Can’t wait to see where we go with this project. #TeamWork #TechInnovation'),
(894, 'https://example.com/sf_bigtech23.jpg', 'Spending the afternoon in the city after work. SF has a way of inspiring creativity. #CityVibes #TechCulture'),
(874, 'https://example.com/sf_bigtech24.jpg', 'After working at a big tech company in SF for a few months, I’ve never felt more motivated. #TechCareer #StartupLife'),
(875, 'https://example.com/sf_bigtech25.jpg', 'Learning so much about the tech industry in SF. Every day is a new opportunity. #TechIndustry #BayAreaTech'),
(896, 'https://example.com/sf_bigtech26.jpg', 'The perks of working in SF: innovation, networking, and endless learning. #SFTech #Networking'),
(897, 'https://example.com/sf_bigtech27.jpg', 'Big tech company life means lots of opportunities to collaborate. Excited for our next big project! #CollaborativeCulture #TechLife'),
(887, 'https://example.com/sf_bigtech28.jpg', 'Working in SF is like being in the center of the tech universe. Every day is a new adventure. #TechUniverse #SFTech'),
(896, 'https://example.com/sf_bigtech29.jpg', 'Took a break to visit the Golden Gate Bridge. Living in SF has its perks! #GoldenGate #SFLiving'),
(899, 'https://example.com/sf_bigtech30.jpg', 'Just wrapped up a meeting with the team. Excited to get started on our next big tech project. #TeamWork #TechProjects'),
(900, 'https://example.com/sf_bigtech31.jpg', 'Starting my day in the office with some of the smartest people in the tech industry. #TechIndustry #Innovation'),
(900, 'https://example.com/sf_bigtech32.jpg', 'The work culture at a big tech company is unique—love the focus on innovation and teamwork. #WorkCulture #TechVibes'),
(901, 'https://example.com/sf_bigtech33.jpg', 'Getting ready for a product launch at work! The energy around here is incredible. #ProductLaunch #SFTech'),
(893, 'https://example.com/sf_bigtech34.jpg', 'Hiking after a week of work in SF. Living here means endless opportunities for adventure. #HikingInSF #TechLife'),
(896, 'https://example.com/sf_bigtech35.jpg', 'Celebrating another successful milestone at work today! Can’t wait for what’s next. #TechMilestones #SFBigTech'),
(896, 'https://example.com/sf_bigtech36.jpg', 'Spending my weekend in the city—such a beautiful place to work and live. #SFWeekend #TechLifestyle'),
(883, 'https://example.com/sf_bigtech37.jpg', 'Working at a big tech company in the Bay Area is challenging, but so rewarding. #TechChallenges #BayAreaLife'),
(875, 'https://example.com/sf_bigtech38.jpg', 'Had a great time networking at a tech conference today. SF is the best place to meet like-minded professionals. #TechNetworking #SFEvents'),
(876, 'https://example.com/sf_bigtech39.jpg', 'Getting through a busy week in SF. But when the work is this exciting, it doesn’t feel like work! #TechExcitement #BayArea'),
(869, 'https://example.com/sf_bigtech40.jpg', 'Excited to start a new project at my tech company. The possibilities are endless here in SF. #TechProjects #StartupVibes'),
(867, 'https://example.com/sf_bigtech41.jpg', 'Grateful for the opportunities to grow in a big tech company. It’s a fast-paced but rewarding environment. #TechGrowth #SFLiving'),
(868, 'https://example.com/sf_bigtech42.jpg', 'Had a great week at work—now it’s time to recharge in the city. #WeekendVibes #TechLife'),
(901, 'https://example.com/sf_bigtech43.jpg', 'Loving the community at my new tech company. It’s amazing to work with such a diverse and talented team. #TechCommunity #StartupLife'),
(894, 'https://example.com/sf_bigtech44.jpg', 'So excited to be part of a big tech company in the Bay Area. I’m learning and growing every day. #TechJourney #SFWork'),
(890, 'https://example.com/sf_bigtech45.jpg', 'Living and working in SF is truly a dream come true. Couldn’t ask for a better place to build my career. #DreamJob #TechLife'),
(893, 'https://example.com/sf_bigtech46.jpg', 'Feeling inspired after today’s team meeting. Excited to dive into the next big project! #TeamMeeting #TechInnovation'),
(870, 'https://example.com/sf_bigtech47.jpg', 'Another amazing week in the tech world here in San Francisco. Grateful for this incredible journey. #TechJourney #SFLife'),
(875, 'https://example.com/sf_bigtech48.jpg', 'Learning so much about cloud computing and tech solutions at work. SF is the best place to be! #CloudTech #SFStartups'),
(872, 'https://example.com/sf_bigtech49.jpg', 'Surrounded by smart, passionate people at work. This is why I love working in tech. #TechLife #SFBigTech'),
(876, 'https://example.com/sf_bigtech50.jpg', 'The journey has just begun, but I’m already excited for the opportunities ahead. #NewBeginnings #SFTech');

INSERT INTO posts (user_id, image_url, caption) 
VALUES 
(1547, 'https://example.com/nyc1.jpg', 'Living my best life in NYC. The energy here is unlike anywhere else! #NYCLiving #CityThatNeverSleeps'),
(1552, 'https://example.com/nyc2.jpg', 'Taking in the view from the top of the Empire State Building today. This city never gets old. #EmpireState #NYCViews'),
(1555, 'https://example.com/nyc3.jpg', 'First weekend in New York City, and I’m loving the hustle and bustle. #NYCWeekend #CityVibes'),
(1555, 'https://example.com/nyc4.jpg', 'From the subway to the skyscrapers, there’s always something exciting happening in NYC. #NYCAdventures #BigApple'),
(1556, 'https://example.com/nyc5.jpg', 'Exploring Central Park this weekend. It’s the perfect escape from the city’s fast pace. #CentralPark #NYCExploration'),
(1556, 'https://example.com/nyc6.jpg', 'Had a great time checking out the Brooklyn Bridge today. Can’t believe I live here now! #BrooklynBridge #NYCLife'),
(1556, 'https://example.com/nyc7.jpg', 'Living in the heart of Manhattan is a dream come true. Every day feels like an adventure. #ManhattanLiving #BigCityLife'),
(1559, 'https://example.com/nyc8.jpg', 'NYC’s food scene is unreal. Just had the best pizza I’ve ever tasted in Little Italy. #NYCFood #PizzaLovers'),
(1559, 'https://example.com/nyc9.jpg', 'Catching a Broadway show tonight—one of the best things about living in New York. #BroadwayNights #NYCEvents'),
(1566, 'https://example.com/nyc10.jpg', 'Riding the subway in NYC has become part of my daily routine. It’s so iconic! #SubwayLife #NYCCommute'),
(1566, 'https://example.com/nyc11.jpg', 'Living in NYC means constant inspiration. The art, the culture, the vibe—it’s all here. #NYCInspiration #UrbanLiving'),
(1566, 'https://example.com/nyc12.jpg', 'Sunset views over the Hudson River never get old. NYC, you’re beautiful. #HudsonRiver #NYCSunset'),
(1413, 'https://example.com/nyc13.jpg', 'Exploring the streets of SoHo and loving the vibe. NYC has some of the best shopping. #SoHoShopping #NYCExploration'),
(1421, 'https://example.com/nyc14.jpg', 'Woke up to the sound of sirens and honking cars. Welcome to New York! #NYCLife #CitySoundtrack'),
(1421, 'https://example.com/nyc15.jpg', 'Caught the ferry to Staten Island today. The skyline views were stunning! #StatenIslandFerry #NYCViews'),
(1421, 'https://example.com/nyc16.jpg', 'Lunch break in Times Square. Can’t believe I get to experience this every day. #TimesSquare #NYCWorkLife'),
(226, 'https://example.com/nyc17.jpg', 'Enjoying a coffee at a café in the East Village. NYC mornings are something else. #EastVillage #CoffeeTime'),
(226, 'https://example.com/nyc18.jpg', 'Had the most amazing bagel from a street cart in Brooklyn. NYC food always hits the spot. #NYCBagels #FoodieLife'),
(828, 'https://example.com/nyc19.jpg', 'Living in NYC means always having something to do. From museums to rooftop bars, there’s never a dull moment. #NYCActivities #CityLiving'),
(226, 'https://example.com/nyc20.jpg', 'Taking a stroll along the High Line today. This city has such a unique charm. #HighLine #NYCViews'),
(325, 'https://example.com/nyc21.jpg', 'Walked through Times Square tonight. It’s like the city never sleeps. #TimesSquare #NYCAtNight');

INSERT INTO posts (user_id, image_url, caption) 
VALUES 
(834, 'https://example.com/nyc22.jpg', 'The view from my apartment is insane. I love waking up to NYC’s skyline every day. #NYCApartment #CityViews'),
(834, 'https://example.com/nyc23.jpg', 'Walking through the streets of Chelsea, where art and culture meet. NYC is always inspiring. #ChelseaArt #NYCLife'),
(834, 'https://example.com/nyc24.jpg', 'Took a bike ride along the West Side Highway today. So many great spots to explore in the city. #NYCBikeRide #WestSideHighway'),
(857, 'https://example.com/nyc25.jpg', 'NYC is the best place to meet new people from all over the world. Loving the diverse culture. #NYCDiversity #GlobalCity'),
(1588, 'https://example.com/nyc26.jpg', 'Saw a street performance in Washington Square Park today. So many talented people in NYC! #WashingtonSquarePark #StreetPerformance'),
(1588, 'https://example.com/nyc27.jpg', 'Loving my new life in NYC. There’s always something to do, something new to try. #NYCAdventures #CityLife'),
(359, 'https://example.com/nyc28.jpg', 'From the Brooklyn Bridge Park to DUMBO, Brooklyn is full of amazing views. #BrooklynViews #NYCExploration'),
(658, 'https://example.com/nyc29.jpg', 'Living in NYC has taught me to appreciate the little things, like a quiet morning walk through the city. #NYCMornings #CityLiving'),
(658, 'https://example.com/nyc30.jpg', 'After work, I love grabbing a drink at a rooftop bar in Manhattan. Can’t beat these views! #RooftopBars #NYCNights'),
(630, 'https://example.com/nyc31.jpg', 'Had a blast at a rooftop party in Brooklyn last night. NYC is the place to be for fun! #BrooklynRooftop #NYCNightLife'),
(630, 'https://example.com/nyc32.jpg', 'Took a weekend trip to upstate New York. Such a great escape from the city’s chaos. #UpstateNY #WeekendGetaway');

INSERT INTO posts (user_id, image_url, caption) 
VALUES 
(226, 'https://example.com/nyc33.jpg', 'Love getting lost in the streets of NYC. Every corner has something new to discover. #NYCExploration #CityAdventures'),
(226, 'https://example.com/nyc34.jpg', 'I’ll never get tired of the views from the Empire State Building. NYC from above is breathtaking. #EmpireStateBuilding #CityViews'),
(226, 'https://example.com/nyc35.jpg', 'Had a great day exploring the museums in NYC. So much art and culture in one place! #NYCMuseums #ArtCulture');

INSERT INTO posts (user_id, image_url, caption) 
VALUES 
(330, 'https://example.com/nyc37.jpg', 'Living in NYC means constant excitement but also learning to slow down and appreciate the moment. #NYCSlowDown'),
(330, 'https://example.com/nyc38.jpg', 'Visiting the Statue of Liberty today. One of the best experiences in NYC! #StatueOfLiberty');

INSERT INTO posts (user_id, image_url, caption) 
VALUES 
(330, 'https://example.com/nyc39.jpg', 'Enjoying the night skyline from the Brooklyn Heights Promenade. This city is magical at night. #BrooklynHeights #NYCViews'),
(139, 'https://example.com/nyc40.jpg', 'Explored the Upper West Side today. NYC’s neighborhoods are so unique and full of charm. #UpperWestSide #NeighborhoodExploration'),
(139, 'https://example.com/nyc41.jpg', 'Visited the 9/11 Memorial today. An emotional experience, but so important. #911Memorial #NYCHistory'),
(139, 'https://example.com/nyc42.jpg', 'Took a walk in Prospect Park today. It’s one of the best hidden gems in Brooklyn. #ProspectPark #Brooklyn'),
(761, 'https://example.com/nyc43.jpg', 'Brunch at a cute café in the West Village. NYC’s brunch scene is unbeatable. #WestVillageBrunch #NYCFood'),
(761, 'https://example.com/nyc44.jpg', 'Spent my Sunday in Chinatown today. NYC is full of diverse cultures and cuisines. #ChinatownNYC #CulturalExploration'),
(761, 'https://example.com/nyc45.jpg', 'Another day, another view. NYC’s skyline still takes my breath away. #NYCViews #Skyscrapers'),
(1000, 'https://example.com/nyc46.jpg', 'Living in NYC means always being surrounded by art, creativity, and ambition. #CreativeCity #NYCArt'),
(226, 'https://example.com/nyc47.jpg', 'Explored the streets of Harlem today. Such rich history and culture in this neighborhood. #HarlemNYC #CulturalTour'),
(630, 'https://example.com/nyc48.jpg', 'New York is the city that never sleeps, and neither do I. #CityThatNeverSleeps #NYCAdventures'),
(630, 'https://example.com/nyc49.jpg', 'Tried a new restaurant in the East Village today. Cant beat NYC’s food scene. #EastVillageEats #NYCFood');

INSERT INTO posts (user_id, image_url, caption) 
VALUES 
(658, 'https://example.com/nyc50.jpg', 'Just had a stroll through Central Park at sunrise. This city is pure magic. #CentralPark #NYCMornings'),
(630, 'https://example.com/nyc51.jpg', 'Exploring the best coffee spots in Brooklyn. #BrooklynCoffee #NYCAdventures');