-- Insert sample users
INSERT INTO users (username, email, password, full_name, profile_picture, bio) VALUES
('user1', 'user1@example.com', 'password1', 'User One', 'https://example.com/user1.jpg', 'Bio of User One'),
('user2', 'user2@example.com', 'password2', 'User Two', 'https://example.com/user2.jpg', 'Bio of User Two'),
('user3', 'user3@example.com', 'password3', 'User Three', 'https://example.com/user3.jpg', 'Bio of User Three'),
('user4', 'user20@example.com', 'password4', 'User Four', 'https://example.com/user4.jpg', 'Bio of User Four'),
('PixelPenguin', 'penguin@example.com', 'password5', 'Arctic Wanderer', 'https://example.com/penguin.jpg', 'Lover of cold vibes and pixels.'),
('SkyChaser', 'sky@example.com', 'password6', 'Skyline Dreamer', 'https://example.com/sky.jpg', 'Capturing the horizons, one photo at a time.'),
('MountainGoat', 'goat@example.com', 'password7', 'Rocky Trails', 'https://example.com/goat.jpg', 'Explorer of cliffs and peaks.'),
('RiverWanderer', 'river@example.com', 'password8', 'Flowing Spirit', 'https://example.com/river.jpg', 'Serenity found in the stream.'),
('DesertFox', 'fox@example.com', 'password9', 'Sahara Rover', 'https://example.com/fox.jpg', 'Finding life in the desert.'),
('TechTrekker', 'techtrekker@example.com', 'password10', 'Digital Nomad', 'https://example.com/trekker.jpg', 'Exploring the world of innovation.');

INSERT INTO users (username, email, password, full_name, profile_picture, bio) VALUES
('TeaLover', 'tea@example.com', 'password1', 'Elizabeth Green', 'https://example.com/tea.jpg', 'Afternoon tea enthusiast.'),
('LondonWalker', 'walker@example.com', 'password2', 'John Sterling', 'https://example.com/london.jpg', 'Exploring the streets of London.'),
('BiscuitHunter', 'biscuit@example.com', 'password3', 'Margaret Brown', 'https://example.com/biscuit.jpg', 'In search of the perfect biscuit.'),
('FoggyMorning', 'foggy@example.com', 'password4', 'Edward Grey', 'https://example.com/foggy.jpg', 'Misty mornings and coffee cups.'),
('ShakespeareFan', 'shakespeare@example.com', 'password5', 'William Page', 'https://example.com/shakespeare.jpg', 'To be or not to be!'),
('UnionJack', 'unionjack@example.com', 'password6', 'Victoria Redford', 'https://example.com/unionjack.jpg', 'Flying the flag with pride.'),
('ThamesRider', 'thames@example.com', 'password7', 'Arthur Lake', 'https://example.com/thames.jpg', 'Cruising down the Thames.'),
('BigBenBeliever', 'bigben@example.com', 'password8', 'Benjamin Clock', 'https://example.com/bigben.jpg', 'Tick-tock through time.'),
('RoyalGardener', 'royalgardener@example.com', 'password9', 'Catherine Bloom', 'https://example.com/garden.jpg', 'Green thumb with a royal touch.'),
('RainyDayDreamer', 'rainyday@example.com', 'password10', 'Harold Weatherby', 'https://example.com/rainyday.jpg', 'Dreaming in the rain.'),
('BoroughBaker', 'baker@example.com', 'password11', 'Sarah Loaf', 'https://example.com/bakery.jpg', 'Bread, pies, and everything nice.'),
('TowerBridgeTrekker', 'towerbridge@example.com', 'password12', 'Daniel Stone', 'https://example.com/towerbridge.jpg', 'Lover of iconic bridges.'),
('PubExplorer', 'pub@example.com', 'password13', 'George Aleman', 'https://example.com/pub.jpg', 'Searching for the coziest pubs.'),
('CambridgeScholar', 'cambridge@example.com', 'password14', 'Emily King', 'https://example.com/cambridge.jpg', 'Books, learning, and tea.'),
('RedBusRider', 'redbus@example.com', 'password15', 'Charles Wheels', 'https://example.com/redbus.jpg', 'Hopping on and off in style.'),
('CountrysideChaser', 'countryside@example.com', 'password16', 'Lydia Fields', 'https://example.com/countryside.jpg', 'The hills are alive with beauty.'),
('CricketFanatic', 'cricket@example.com', 'password17', 'James Batson', 'https://example.com/cricket.jpg', 'Bowled over by cricket.'),
('CottageCoreDream', 'cottagecore@example.com', 'password18', 'Alice Meadow', 'https://example.com/cottage.jpg', 'Rustic charm, always.'),
('StonehengeSeeker', 'stonehenge@example.com', 'password19', 'Oliver Circle', 'https://example.com/stonehenge.jpg', 'Mysteries of the ancient stones.'),
('OxfordThinker', 'oxford@example.com', 'password20', 'Henry Brainwood', 'https://example.com/oxford.jpg', 'Wisdom in the dreaming spires.'),
('TeaAndBooks', 'teaandbooks@example.com', 'password21', 'Charlotte Turner', 'https://example.com/teaandbooks.jpg', 'Perfect pairing: tea and novels.'),
('CozyFireplace', 'fireplace@example.com', 'password22', 'Lucy Warmth', 'https://example.com/fireplace.jpg', 'Fireside chats and marshmallows.'),
('CastlesAndCrowns', 'castles@example.com', 'password23', 'Philip Crownstone', 'https://example.com/castles.jpg', 'History and grandeur everywhere.'),
('LakeDistrictLover', 'lakedistrict@example.com', 'password24', 'Anna Waters', 'https://example.com/lakedistrict.jpg', 'The lakes are my happy place.'),
('YorkshirePudding', 'yorkshire@example.com', 'password25', 'Frederick Tasty', 'https://example.com/yorkshire.jpg', 'Foodie with a northern twist.'),
('ScottishHighlander', 'scottish@example.com', 'password26', 'Fiona Braveheart', 'https://example.com/highlands.jpg', 'Mountains and misty glens.'),
('CharmingChelsea', 'chelsea@example.com', 'password27', 'Sophia Lane', 'https://example.com/chelsea.jpg', 'Exploring stylish corners.'),
('GreenwichGazer', 'greenwich@example.com', 'password28', 'Samuel Time', 'https://example.com/greenwich.jpg', 'Setting my clock to Greenwich Mean Time.'),
('BuckinghamDreamer', 'buckingham@example.com', 'password29', 'Diana Windsor', 'https://example.com/buckingham.jpg', 'Palaces, gardens, and dreams.'),
('HamptonHistorian', 'hampton@example.com', 'password30', 'Edward Hall', 'https://example.com/hampton.jpg', 'Timeless tales from the court.'),
('QueenBee', 'queenbee@example.com', 'password31', 'Victoria Majesty', 'https://example.com/queenbee.jpg', 'Ruling my little kingdom.'),
('RegentStroller', 'regent@example.com', 'password32', 'Alexander Lane', 'https://example.com/regent.jpg', 'Walking through history.'),
('PortobelloPicker', 'portobello@example.com', 'password33', 'Amelia Market', 'https://example.com/portobello.jpg', 'Finding treasures in the market.'),
('HydeParkJogger', 'hydepark@example.com', 'password34', 'Thomas Sprint', 'https://example.com/hydepark.jpg', 'Running through iconic views.'),
('VintageVictoria', 'vintagevictoria@example.com', 'password35', 'Emily Lace', 'https://example.com/vintage.jpg', 'Timeless and elegant always.'),
('LondonEyeSeer', 'londoneye@example.com', 'password36', 'Eleanor View', 'https://example.com/londoneye.jpg', 'Seeing the city from above.'),
('RoyalTeaParty', 'royalteaparty@example.com', 'password37', 'Isabelle Cup', 'https://example.com/teaparty.jpg', 'Sipping tea with a twist.'),
('AbbeyFanatic', 'abbey@example.com', 'password38', 'Matthew Bells', 'https://example.com/abbey.jpg', 'Echoes of history in stone.'),
('LakePoet', 'lakepoet@example.com', 'password39', 'Dorothy Wordsworth', 'https://example.com/lakepoet.jpg', 'Writing in the stillness.'),
('EnglishRose', 'rose@example.com', 'password40', 'Rosemary Petals', 'https://example.com/rose.jpg', 'Blooms of inspiration.'),
('VictorianVibes', 'victorianvibes@example.com', 'password41', 'Arthur Dickens', 'https://example.com/victorian.jpg', 'A step back in time.'),
('HedgehogLover', 'hedgehog@example.com', 'password42', 'Hannah Prickles', 'https://example.com/hedgehog.jpg', 'Nature’s little wonders.'),
('ThistleAndThames', 'thistleandthames@example.com', 'password43', 'William Scott', 'https://example.com/thistle.jpg', 'A blend of north and south.'),
('CountryLane', 'countrylane@example.com', 'password44', 'Laura Fielding', 'https://example.com/countrylane.jpg', 'The winding roads of beauty.'),
('LondonLights', 'londonlights@example.com', 'password45', 'Olivia Glow', 'https://example.com/londonlights.jpg', 'Bright nights in the city.'),
('CamdenCrafter', 'camden@example.com', 'password46', 'Daniel Crafton', 'https://example.com/camden.jpg', 'Creative vibes in the market.'),
('GreenFields', 'greenfields@example.com', 'password47', 'Emily Clover', 'https://example.com/greenfields.jpg', 'Rolling hills forever.'),
('RainyUmbrella', 'umbrella@example.com', 'password48', 'Harry Weather', 'https://example.com/umbrella.jpg', 'Under my umbrella.'),
('DoverExplorer', 'dover@example.com', 'password49', 'Christopher Cliff', 'https://example.com/dover.jpg', 'White cliffs and blue seas.'),
('BristolBridges', 'bristol@example.com', 'password50', 'Charlotte Spans', 'https://example.com/bristol.jpg', 'Connecting the dots.');

INSERT INTO users (username, email, password, full_name, profile_picture, bio) VALUES
('StarsAndStripes', 'stars@example.com', 'password1', 'Samuel Freedom', 'https://example.com/stars.jpg', 'Patriot at heart.'),
('NYCPizzaLover', 'pizza@example.com', 'password2', 'Alex Brooklyn', 'https://example.com/pizza.jpg', 'In crust we trust.'),
('Route66Rider', 'route66@example.com', 'password3', 'Chris Highway', 'https://example.com/route66.jpg', 'Riding the American dream.'),
('GoldenGateGazer', 'goldengate@example.com', 'password4', 'Samantha Bridge', 'https://example.com/goldengate.jpg', 'Views from the bridge.'),
('BBQKing', 'bbqking@example.com', 'password5', 'Jordan Smoke', 'https://example.com/bbq.jpg', 'Meat, fire, and flavor.'),
('TexasRancher', 'texas@example.com', 'password6', 'Taylor Lasso', 'https://example.com/texas.jpg', 'Hats, boots, and sunsets.'),
('CaliforniaDreamer', 'californiadreamer@example.com', 'password7', 'Jessica Malibu', 'https://example.com/california.jpg', 'Beach days and starry nights.'),
('LibertyBellFan', 'libertybell@example.com', 'password8', 'Franklin Bell', 'https://example.com/libertybell.jpg', 'Ringing in freedom.'),
('MiamiSunshine', 'miamisunshine@example.com', 'password9', 'Sophia Ocean', 'https://example.com/miami.jpg', 'Living for the waves.'),
('AlaskaExplorer', 'alaska@example.com', 'password10', 'Hannah Glacier', 'https://example.com/alaska.jpg', 'Chasing northern lights.'),
('ChicagoDeepDish', 'deepdish@example.com', 'password11', 'Matthew Slice', 'https://example.com/deepdish.jpg', 'Windy city foodie.'),
('GrandCanyonHiker', 'grandcanyon@example.com', 'password12', 'Bryan Canyon', 'https://example.com/grandcanyon.jpg', 'The edge of wonder.'),
('JazzAndBeignets', 'jazz@example.com', 'password13', 'Lila NewOrleans', 'https://example.com/jazz.jpg', 'Sweet tunes and sweeter treats.'),
('SeattleBrews', 'seattle@example.com', 'password14', 'Ethan Coffee', 'https://example.com/seattle.jpg', 'Caffeine and rain.'),
('RockyMountainClimber', 'rockies@example.com', 'password15', 'Emily Peak', 'https://example.com/rockies.jpg', 'Adventure is out there.'),
('DisneyFanatic', 'disney@example.com', 'password16', 'Mickey Fan', 'https://example.com/disney.jpg', 'Magic is everywhere.'),
('SouthernCharm', 'southern@example.com', 'password17', 'Charlotte Savannah', 'https://example.com/southern.jpg', 'Y’all come back now.'),
('YosemiteWanderer', 'yosemite@example.com', 'password18', 'Jack Valley', 'https://example.com/yosemite.jpg', 'Lost in nature.'),
('HollywoodDreamer', 'hollywood@example.com', 'password19', 'Taylor Lights', 'https://example.com/hollywood.jpg', 'Roll the credits.'),
('VegasLights', 'vegaslights@example.com', 'password20', 'Cassidy Jackpot', 'https://example.com/vegas.jpg', 'Bright lights, big city.'),
('BroadwayStar', 'broadway@example.com', 'password21', 'Ella Spotlight', 'https://example.com/broadway.jpg', 'The stage is set.'),
('SiliconValleyTech', 'siliconvalley@example.com', 'password22', 'Logan Code', 'https://example.com/siliconvalley.jpg', 'Innovation is my passion.'),
('TennesseeWhiskey', 'whiskey@example.com', 'password23', 'Lucas Distiller', 'https://example.com/whiskey.jpg', 'Smooth as Tennessee.'),
('CapeCodCruiser', 'capecod@example.com', 'password24', 'Isabella Harbor', 'https://example.com/capecod.jpg', 'Sailing through the breeze.'),
('HawaiiAloha', 'hawaii@example.com', 'password25', 'Noah Wave', 'https://example.com/hawaii.jpg', 'Aloha vibes only.'),
('StatueOfLiberty', 'statueofliberty@example.com', 'password26', 'Grace Ellis', 'https://example.com/statueofliberty.jpg', 'Beacon of freedom.'),
('CowboyBoots', 'cowboyboots@example.com', 'password27', 'Riley Spurs', 'https://example.com/cowboyboots.jpg', 'Giddy up, partner.'),
('BostonRedSox', 'redsox@example.com', 'password28', 'Elliot Fenway', 'https://example.com/redsox.jpg', 'Baseball and chowder.'),
('SmokyMountainView', 'smokymountains@example.com', 'password29', 'Jasmine Mist', 'https://example.com/smokies.jpg', 'Foggy horizons forever.'),
('SpaceCenterFan', 'spacecenter@example.com', 'password30', 'Caleb Apollo', 'https://example.com/spacecenter.jpg', 'Houston, we have liftoff.'),
('FloridaKeysSunset', 'floridakeys@example.com', 'password31', 'Savannah Horizon', 'https://example.com/floridakeys.jpg', 'Sunset chaser.'),
('NiagaraFalls', 'niagara@example.com', 'password32', 'Daniel Splash', 'https://example.com/niagara.jpg', 'Roaring waters ahead.'),
('TexasBBQLover', 'texasbbq@example.com', 'password33', 'Jaxon Smoke', 'https://example.com/texasbbq.jpg', 'Barbecue is life.'),
('BayAreaBiker', 'bayarea@example.com', 'password34', 'Sierra Pedals', 'https://example.com/bayarea.jpg', 'Rolling through the hills.'),
('DenverBrews', 'denver@example.com', 'password35', 'Hunter Craft', 'https://example.com/denver.jpg', 'Cheers to craft beer.'),
('YellowstoneExplorer', 'yellowstone@example.com', 'password36', 'Ella Geyser', 'https://example.com/yellowstone.jpg', 'Nature at its finest.'),
('SaltLakeSkier', 'saltlake@example.com', 'password37', 'Mason Snow', 'https://example.com/snow.jpg', 'Powder days forever.'),
('PhoenixRising', 'phoenix@example.com', 'password38', 'Avery Blaze', 'https://example.com/phoenix.jpg', 'Heat and heart.'),
('CaliSurfer', 'calisurfer@example.com', 'password39', 'Brandon Wave', 'https://example.com/surf.jpg', 'Catch the perfect wave.'),
('BostonTeaParty', 'bostontea@example.com', 'password40', 'Emily Harbor', 'https://example.com/boston.jpg', 'Revolutionary vibes.'),
('KeyWestChill', 'keywest@example.com', 'password41', 'Harper Tides', 'https://example.com/keywest.jpg', 'Island life forever.'),
('NashvilleStrings', 'nashville@example.com', 'password42', 'Madison Harmony', 'https://example.com/nashville.jpg', 'Music is my soul.'),
('AlamoAdventurer', 'alamo@example.com', 'password43', 'Declan Remember', 'https://example.com/alamo.jpg', 'History and bravery.'),
('MinneapolisLakes', 'minneapolis@example.com', 'password44', 'Autumn North', 'https://example.com/minneapolis.jpg', 'Land of 10,000 lakes.'),
('SedonaHiker', 'sedona@example.com', 'password45', 'Ruby Canyon', 'https://example.com/sedona.jpg', 'Red rock wonderland.'),
('WashingtonApple', 'washington@example.com', 'password46', 'Grace Orchard', 'https://example.com/washington.jpg', 'An apple a day.'),
('BigSkyDreamer', 'bigsky@example.com', 'password47', 'Skyler Montana', 'https://example.com/bigsky.jpg', 'Under the endless sky.'),
('MountRushmore', 'mountrushmore@example.com', 'password48', 'Parker Presidents', 'https://example.com/rushmore.jpg', 'Carving memories.'),
('OregonTrails', 'oregon@example.com', 'password49', 'Dakota River', 'https://example.com/oregon.jpg', 'The great journey west.'),
('ZionAdventurer', 'zion@example.com', 'password50', 'Jordan Cliff', 'https://example.com/zion.jpg', 'Scaling new heights.');

INSERT INTO users (username, email, password, full_name, profile_picture, bio) VALUES
('GoldenCoastGal', 'goldencoast@example.com', 'password1', 'Sunny Malibu', 'https://example.com/goldencoast.jpg', 'Beach vibes and golden skies.'),
('HollywoodHustler', 'hollywoodhustler@example.com', 'password2', 'Taylor Fame', 'https://example.com/hollywood.jpg', 'Living the dream.'),
('BayAreaVibes', 'bayarea@example.com', 'password3', 'Jordan Oakland', 'https://example.com/bayarea.jpg', 'Tech, art, and life.'),
('SurfinSantaCruz', 'santacruz@example.com', 'password4', 'Kai Wave', 'https://example.com/santacruz.jpg', 'Hang ten and feel alive.'),
('SierraHiker', 'sierrahiker@example.com', 'password5', 'Aspen Trail', 'https://example.com/sierra.jpg', 'Climbing high, living free.'),
('CaliSunset', 'calisunset@example.com', 'password6', 'Mia Horizon', 'https://example.com/sunset.jpg', 'Where the sky meets the sea.'),
('PalmSpringsChill', 'palmsprings@example.com', 'password7', 'Riley Oasis', 'https://example.com/palmsprings.jpg', 'Desert sunsets are my muse.'),
('WineCountryDream', 'winecountry@example.com', 'password8', 'Sophia Napa', 'https://example.com/winecountry.jpg', 'Sipping my way through life.'),
('VeniceBoardwalk', 'veniceboardwalk@example.com', 'password9', 'Tyler Skater', 'https://example.com/venice.jpg', 'Life on wheels.'),
('LagunaLover', 'laguna@example.com', 'password10', 'Ella Laguna', 'https://example.com/laguna.jpg', 'Paradise found.'),
('RedwoodRanger', 'redwood@example.com', 'password11', 'Sage Forest', 'https://example.com/redwood.jpg', 'Among the giants.'),
('LaLaLandLife', 'lalaland@example.com', 'password12', 'Luna Angeles', 'https://example.com/lalaland.jpg', 'City of stars.'),
('CarmelCoastline', 'carmel@example.com', 'password13', 'Evan Pebble', 'https://example.com/carmel.jpg', 'Coastal charm and calm.'),
('SanDiegoSurfer', 'sandiego@example.com', 'password14', 'Blake Wave', 'https://example.com/sandiego.jpg', 'Living for the swell.'),
('OCFashionista', 'ocfashionista@example.com', 'password15', 'Chloe Orange', 'https://example.com/oc.jpg', 'Style with a splash of sun.'),
('BigBearAdventurer', 'bigbear@example.com', 'password16', 'Hunter Summit', 'https://example.com/bigbear.jpg', 'Snow days and stargazing.'),
('SacramentoSoul', 'sacramento@example.com', 'password17', 'Logan River', 'https://example.com/sacramento.jpg', 'Heart of California.'),
('CoachellaChic', 'coachella@example.com', 'password18', 'Willow Desert', 'https://example.com/coachella.jpg', 'Music, art, and love.'),
('BeachCityBreeze', 'beachcity@example.com', 'password19', 'Parker Pacific', 'https://example.com/beachcity.jpg', 'Living by the waves.'),
('MontereyMermaid', 'monterey@example.com', 'password20', 'Isla Cove', 'https://example.com/monterey.jpg', 'Life’s better underwater.'),
('LakeTahoeDreamer', 'laketahoe@example.com', 'password21', 'Brooke Alpine', 'https://example.com/tahoe.jpg', 'Crystal clear and carefree.'),
('SanFranciscoSoul', 'sanfran@example.com', 'password22', 'Elliot Bridge', 'https://example.com/sanfran.jpg', 'Golden Gate dreams.'),
('HollywoodSunshine', 'hollywoodsunshine@example.com', 'password23', 'Sierra Spotlight', 'https://example.com/hollywoodsunshine.jpg', 'Catch me on the set.'),
('MalibuMagic', 'malibumagic@example.com', 'password24', 'Chelsea Ocean', 'https://example.com/malibu.jpg', 'Waves and wonder.'),
('JoshuaTreeSeeker', 'joshuatree@example.com', 'password25', 'Phoenix Cactus', 'https://example.com/joshuatree.jpg', 'Under desert stars.'),
('YosemiteTrailblazer', 'yosemitetrail@example.com', 'password26', 'Aspen Valley', 'https://example.com/yosemite.jpg', 'Nature’s cathedral.'),
('SantaBarbaraBreeze', 'santabarbara@example.com', 'password27', 'Ivy Coast', 'https://example.com/santabarbara.jpg', 'Living the coastal life.'),
('GoldenGateGrin', 'goldengategrin@example.com', 'password28', 'Jamie Skyline', 'https://example.com/goldengate.jpg', 'Where fog meets magic.'),
('PacificCoastChaser', 'pacificcoast@example.com', 'password29', 'Cameron Tides', 'https://example.com/pacificcoast.jpg', 'Roads less traveled.'),
('OCGlow', 'ocglow@example.com', 'password30', 'Amber Laguna', 'https://example.com/ocglow.jpg', 'Sun-kissed and glowing.'),
('SantaMonicaStar', 'santamonica@example.com', 'password31', 'Mason Pier', 'https://example.com/santamonica.jpg', 'Pier-side peace.'),
('SocalSunrise', 'socalsunrise@example.com', 'password32', 'Dylan Horizon', 'https://example.com/sunrise.jpg', 'Rise and shine.'),
('HollywoodLights', 'hollywoodlights@example.com', 'password33', 'Taylor Glimmer', 'https://example.com/lights.jpg', 'The city that shines.'),
('NapaValleyVine', 'napavalley@example.com', 'password34', 'Vincent Grape', 'https://example.com/napa.jpg', 'Cheers to life.'),
('BigSurWanderer', 'bigsur@example.com', 'password35', 'Autumn Cliff', 'https://example.com/bigsur.jpg', 'The edge of beauty.'),
('SanJoseCoder', 'sanjose@example.com', 'password36', 'Ethan Code', 'https://example.com/sanjose.jpg', 'Innovation in my veins.'),
('VeniceSunset', 'venicesunset@example.com', 'password37', 'Leila Glow', 'https://example.com/veniceglow.jpg', 'Art, life, and sunsets.'),
('LongBeachSurfer', 'longbeach@example.com', 'password38', 'Brandon Tide', 'https://example.com/longbeach.jpg', 'Wave chaser.'),
('CaliDreaming', 'calidreaming@example.com', 'password39', 'Sky Dreamer', 'https://example.com/calidream.jpg', 'California state of mind.'),
('SantaCruzSoul', 'santacruzsoul@example.com', 'password40', 'Harper Skater', 'https://example.com/skater.jpg', 'Roll with the flow.'),
('MendocinoWaves', 'mendocino@example.com', 'password41', 'River Ocean', 'https://example.com/mendocino.jpg', 'Where land meets sea.'),
('BeverlyHillsVibes', 'beverlyhills@example.com', 'password42', 'Sophia Luxe', 'https://example.com/beverlyhills.jpg', 'Living lavishly.'),
('SoCalStargazer', 'socalstargazer@example.com', 'password43', 'Astrid Glow', 'https://example.com/stargazer.jpg', 'Eyes on the stars.'),
('LagunaSands', 'lagunasands@example.com', 'password44', 'Riley Shore', 'https://example.com/lagunasands.jpg', 'Where dreams meet the ocean.'),
('RedwoodTrail', 'redwoodtrail@example.com', 'password45', 'Cedar Grove', 'https://example.com/redwoodtrail.jpg', 'Under the canopy.'),
('JoshuaSky', 'joshuasky@example.com', 'password46', 'Luna Oasis', 'https://example.com/desertsky.jpg', 'Desert days, starry nights.'),
('GoldenHourGlow', 'goldenhour@example.com', 'password47', 'Mia Horizon', 'https://example.com/goldenhour.jpg', 'Chasing the light.'),
('CaliSierraStar', 'calisierra@example.com', 'password48', 'Jasper Peak', 'https://example.com/sierra.jpg', 'Above the clouds.'),
('HollywoodGlam', 'hollywoodglam@example.com', 'password49', 'Ella Fame', 'https://example.com/hollywoodglam.jpg', 'Lights, camera, action.'),
('MalibuSerenity', 'malibuserenity@example.com', 'password50', 'Layla Breeze', 'https://example.com/malibu.jpg', 'Peace by the waves.');

INSERT INTO users (username, email, password, full_name, profile_picture, bio) VALUES
('AlohaWave', 'aloha@example.com', 'password1', 'Kai Hoku', 'https://example.com/aloha.jpg', 'Living the island life.'),
('SunsetHula', 'sunsethula@example.com', 'password2', 'Leilani Kalani', 'https://example.com/sunset.jpg', 'Dancing under the setting sun.'),
('IslandVibes', 'islandvibes@example.com', 'password3', 'Nalu Kea', 'https://example.com/islandvibes.jpg', 'Salt in the air, sand in my hair.'),
('PacificDreamer', 'pacificdreamer@example.com', 'password4', 'Malia Moana', 'https://example.com/pacific.jpg', 'Chasing waves and sunsets.'),
('HulaHarmony', 'hulaharmony@example.com', 'password5', 'Koa Malu', 'https://example.com/hula.jpg', 'Strumming my ukulele.'),
('MauiSurfer', 'mauisurfer@example.com', 'password6', 'Lani Kai', 'https://example.com/maui.jpg', 'Surf’s up in paradise.'),
('OhanaHeart', 'ohanaheart@example.com', 'password7', 'Keanu Lani', 'https://example.com/ohana.jpg', 'Family first, always.'),
('TropicalBreeze', 'tropicalbreeze@example.com', 'password8', 'Pua Kahakai', 'https://example.com/breeze.jpg', 'Breathing in island air.'),
('LavaFlow', 'lavaflow@example.com', 'password9', 'Ikaika Pele', 'https://example.com/lava.jpg', 'Fire in my soul.'),
('MolokaiMagic', 'molokaimagic@example.com', 'password10', 'Noelani Wai', 'https://example.com/molokai.jpg', 'Hidden gems and aloha.'),
('HawaiiSunrise', 'hawaiisunrise@example.com', 'password11', 'Kalani Maluhia', 'https://example.com/sunrise.jpg', 'Awakening with the sun.'),
('PineappleParadise', 'pineappleparadise@example.com', 'password12', 'Makani Olu', 'https://example.com/pineapple.jpg', 'Sweet and golden.'),
('AlohaSpirit', 'alohaspirit@example.com', 'password13', 'Halia Anela', 'https://example.com/spirit.jpg', 'Kindness, always.'),
('WaikikiWaves', 'waikiki@example.com', 'password14', 'Lehua Nani', 'https://example.com/waikiki.jpg', 'Life by the shore.'),
('BigIslandSoul', 'bigisland@example.com', 'password15', 'Kanoa Pali', 'https://example.com/bigisland.jpg', 'Mountains and oceans.'),
('KonaBreeze', 'konabreeze@example.com', 'password16', 'Maile Kona', 'https://example.com/kona.jpg', 'Coffee and calm mornings.'),
('HonuHaven', 'honuhaven@example.com', 'password17', 'Kai Honu', 'https://example.com/honu.jpg', 'Swimming with turtles.'),
('ParadiseGlow', 'paradiseglow@example.com', 'password18', 'Meilani Kai', 'https://example.com/paradise.jpg', 'Glow of the islands.'),
('SurfShaka', 'surfshaka@example.com', 'password19', 'Nani Keiki', 'https://example.com/surf.jpg', 'Ride the waves, live the dream.'),
('VolcanoVibes', 'volcanovibes@example.com', 'password20', 'Iolana Hale', 'https://example.com/volcano.jpg', 'Where earth meets fire.'),
('HulaHaven', 'hulahaven@example.com', 'password21', 'Pono Alani', 'https://example.com/hulahaven.jpg', 'Dancing to island rhythms.'),
('OceanOhana', 'oceanohana@example.com', 'password22', 'Makana Wai', 'https://example.com/oceanohana.jpg', 'Family of the sea.'),
('AlohaAdventure', 'alohaadventure@example.com', 'password23', 'Kaliko Lani', 'https://example.com/adventure.jpg', 'Exploring every shore.'),
('TikiTales', 'tikitales@example.com', 'password24', 'Mana Hoku', 'https://example.com/tiki.jpg', 'Stories under the stars.'),
('KauaiDream', 'kauaidream@example.com', 'password25', 'Lilia Makai', 'https://example.com/kauai.jpg', 'Garden isle, endless beauty.'),
('IslandExplorer', 'islandexplorer@example.com', 'password26', 'Kekoa Hale', 'https://example.com/explorer.jpg', 'Every wave is a story.'),
('PacificParadise', 'pacificparadise@example.com', 'password27', 'Ala Moana', 'https://example.com/paradise.jpg', 'Living the Pacific dream.'),
('SunsetShaka', 'sunsetshaka@example.com', 'password28', 'Liko Keiki', 'https://example.com/shaka.jpg', 'Sunsets and surfboards.'),
('LanaiLover', 'lanailover@example.com', 'password29', 'Nohea Lani', 'https://example.com/lanai.jpg', 'Solitude and serenity.'),
('HawaiiHeart', 'hawaiiheart@example.com', 'password30', 'Pele Malu', 'https://example.com/heart.jpg', 'Passion and paradise.'),
('TropicalSoul', 'tropicalsoul@example.com', 'password31', 'Kaiolohia Nalu', 'https://example.com/tropical.jpg', 'Where the ocean meets my soul.'),
('MolokaiMagic', 'molokaimagic@example.com', 'password32', 'Hoku Kahakai', 'https://example.com/magic.jpg', 'Peace in every corner.'),
('PearlHarborHope', 'pearlharbor@example.com', 'password33', 'Kalena Kai', 'https://example.com/pearl.jpg', 'Honoring the past, embracing the future.'),
('HaleakalaHiker', 'haleakala@example.com', 'password34', 'Lilo Hale', 'https://example.com/haleakala.jpg', 'Above the clouds.'),
('OahuOcean', 'oahu@example.com', 'password35', 'Nai’a Moana', 'https://example.com/oahu.jpg', 'Island harmony.'),
('PolynesianDream', 'polynesian@example.com', 'password36', 'Keani Ola', 'https://example.com/polynesia.jpg', 'Islands in my heart.'),
('SurfShoreline', 'surfshoreline@example.com', 'password37', 'Kai Nalu', 'https://example.com/surfshore.jpg', 'Every wave tells a story.'),
('OhanaOasis', 'ohanaoasis@example.com', 'password38', 'Lana Wai', 'https://example.com/ohanaoasis.jpg', 'Home is where the ocean is.'),
('IslandGlow', 'islandglow@example.com', 'password39', 'Malia Anela', 'https://example.com/glow.jpg', 'Shining with aloha.'),
('HonuHarmony', 'honuharmony@example.com', 'password40', 'Koa Kahuna', 'https://example.com/honu.jpg', 'Turtle tales.'),
('WaiKani', 'waikani@example.com', 'password41', 'Kalani Ola', 'https://example.com/waikani.jpg', 'Waterfalls and whispers.'),
('ParadisePath', 'paradisepath@example.com', 'password42', 'Pua Halia', 'https://example.com/path.jpg', 'Walking the aloha way.'),
('HulaDancer', 'huladancer@example.com', 'password43', 'Nohea Malie', 'https://example.com/hula.jpg', 'The rhythm of my soul.'),
('IslandDreams', 'islanddreams@example.com', 'password44', 'Anuhea Moana', 'https://example.com/dreams.jpg', 'Living on island time.'),
('KauaiSunrise', 'kauaisunrise@example.com', 'password45', 'Lehua Nalu', 'https://example.com/sunrise.jpg', 'Greeting the day with aloha.'),
('PacificGlow', 'pacificglow@example.com', 'password46', 'Hoku Kai', 'https://example.com/pacificglow.jpg', 'Glow of the Pacific.'),
('AlohaAdventures', 'alohaadventures@example.com', 'password47', 'Makana Nui', 'https://example.com/adventures.jpg', 'Embracing every journey.'),
('WaimeaWanderer', 'waimeawanderer@example.com', 'password48', 'Iolana Moana', 'https://example.com/waimea.jpg', 'Exploring every wave.'),
('HawaiianSoul', 'hawaiiansoul@example.com', 'password49', 'Kainoa Wai', 'https://example.com/soul.jpg', 'Island life forever.'),
('ParadiseDream', 'paradisedream@example.com', 'password50', 'Lani Nalu', 'https://example.com/dream.jpg', 'Chasing sunsets and rainbows.');

INSERT INTO users (username, email, password, full_name, profile_picture, bio) VALUES
('BavarianWanderer', 'bavarian@example.com', 'password1', 'Lukas Müller', 'https://example.com/bavarian.jpg', 'Exploring the Alps and enjoying pretzels.'),
('BerlinExplorer', 'berlinexplorer@example.com', 'password2', 'Anna Schmidt', 'https://example.com/berlin.jpg', 'Discovering Berlin’s hidden gems.'),
('BlackForestSoul', 'blackforest@example.com', 'password3', 'Maximilian Fischer', 'https://example.com/blackforest.jpg', 'Hiking through the Schwarzwald.'),
('HamburgHarbor', 'hamburgharbor@example.com', 'password4', 'Sophia Meyer', 'https://example.com/hamburg.jpg', 'Sea breezes and sunsets in Hamburg.'),
('RhinelandRider', 'rhinelandrider@example.com', 'password5', 'Felix Becker', 'https://example.com/rhineland.jpg', 'Cycling along the Rhine River.'),
('FrankfurtSkyline', 'frankfurt@example.com', 'password6', 'Marie Weber', 'https://example.com/frankfurt.jpg', 'City lights and modern vibes.'),
('OktoberfestFan', 'oktoberfestfan@example.com', 'password7', 'Jonas Wagner', 'https://example.com/oktoberfest.jpg', 'Prost! Enjoying life in Bavaria.'),
('MunichMoments', 'munichmoments@example.com', 'password8', 'Lea Schulz', 'https://example.com/munich.jpg', 'Bavarian charm and culture.'),
('BrandenburgBeauty', 'brandenburg@example.com', 'password9', 'Paul Neumann', 'https://example.com/brandenburg.jpg', 'Peaceful lakes and scenic routes.'),
('DresdenDreamer', 'dresdendreamer@example.com', 'password10', 'Clara Hoffmann', 'https://example.com/dresden.jpg', 'Baroque beauty and history.'),
('BremenBreeze', 'bremenbreeze@example.com', 'password11', 'Tim Lehmann', 'https://example.com/bremen.jpg', 'Northern charm and maritime heritage.'),
('HessenHiker', 'hessenhiker@example.com', 'password12', 'Emma Keller', 'https://example.com/hessen.jpg', 'Trails and tranquility in Hessen.'),
('CologneCathedral', 'colognecathedral@example.com', 'password13', 'Julian Klein', 'https://example.com/cologne.jpg', 'Admiring the Dom and the Rhine.'),
('StuttgartStars', 'stuttgartstars@example.com', 'password14', 'Mia Wolf', 'https://example.com/stuttgart.jpg', 'Cars, vineyards, and stargazing.'),
('HeidelbergHaven', 'heidelberghaven@example.com', 'password15', 'Leon Braun', 'https://example.com/heidelberg.jpg', 'Romantic castles and river views.'),
('LeipzigLife', 'leipziglife@example.com', 'password16', 'Hanna Wagner', 'https://example.com/leipzig.jpg', 'Art, music, and creativity in Leipzig.'),
('BavariaExplorer', 'bavariaexplorer@example.com', 'password17', 'Alexander König', 'https://example.com/bavaria.jpg', 'Exploring castles and mountains.'),
('DortmundDreamer', 'dortmunddreamer@example.com', 'password18', 'Lara Böhm', 'https://example.com/dortmund.jpg', 'Soccer, beer, and good vibes.'),
('HanoverHarmony', 'hanoverharmony@example.com', 'password19', 'Matthias Lange', 'https://example.com/hanover.jpg', 'Peaceful parks and historic streets.'),
('NurembergNotes', 'nurembergnotes@example.com', 'password20', 'Johanna Busch', 'https://example.com/nuremberg.jpg', 'Living in medieval magic.'),
('GermanTrails', 'germantrails@example.com', 'password21', 'Simon Keller', 'https://example.com/trails.jpg', 'Adventure across the countryside.'),
('RuhrRiverRun', 'ruhr@example.com', 'password22', 'Nina Schäfer', 'https://example.com/ruhr.jpg', 'Running through industrial beauty.'),
('ThuringiaTales', 'thuringia@example.com', 'password23', 'Philipp Hartmann', 'https://example.com/thuringia.jpg', 'Land of forests and traditions.'),
('BavarianBliss', 'bavarianbliss@example.com', 'password24', 'Isabel Stein', 'https://example.com/bliss.jpg', 'Finding joy in the Alps.'),
('LakeConstanceLife', 'lakeconstance@example.com', 'password25', 'David Krüger', 'https://example.com/constance.jpg', 'Sailing and serenity by the lake.'),
('MoselleMagic', 'mosellemagic@example.com', 'password26', 'Lisa Berger', 'https://example.com/moselle.jpg', 'Wine country and river breezes.'),
('SchlossFan', 'schlossfan@example.com', 'password27', 'Christian Horn', 'https://example.com/schloss.jpg', 'Exploring Germany’s stunning castles.'),
('GermanWanderlust', 'wanderlust@example.com', 'password28', 'Laura Fuchs', 'https://example.com/wanderlust.jpg', 'On a journey through Germany.'),
('LübeckLover', 'lubecklover@example.com', 'password29', 'Florian Vogel', 'https://example.com/lubeck.jpg', 'Marzipan and medieval charm.'),
('HarzHiker', 'harzhiker@example.com', 'password30', 'Elisa Haas', 'https://example.com/harz.jpg', 'Walking through enchanted forests.'),
('BadenBeauty', 'badenbeauty@example.com', 'password31', 'Markus Weiß', 'https://example.com/baden.jpg', 'Spas, wines, and rolling hills.'),
('DüsseldorfDreamer', 'dusseldorfdreamer@example.com', 'password32', 'Katrin Bauer', 'https://example.com/dusseldorf.jpg', 'Art, fashion, and river vibes.'),
('EifelExplorer', 'eifelexplorer@example.com', 'password33', 'Tom Richter', 'https://example.com/eifel.jpg', 'Volcanic landscapes and peace.'),
('GermanVista', 'germanvista@example.com', 'password34', 'Amelie Frank', 'https://example.com/vista.jpg', 'Views across the nation.'),
('RügenRider', 'rugen@example.com', 'password35', 'Patrick Simon', 'https://example.com/rugen.jpg', 'Cliffs, bikes, and beaches.'),
('BerlinBreeze', 'berlinbreeze@example.com', 'password36', 'Linda Krause', 'https://example.com/berlinbreeze.jpg', 'Urban adventures and history.'),
('WürzburgWaves', 'wurzburg@example.com', 'password37', 'Felix Albrecht', 'https://example.com/wurzburg.jpg', 'Living by the Main.'),
('SaxonSerenity', 'saxonserenity@example.com', 'password38', 'Eva Lorenz', 'https://example.com/saxon.jpg', 'Tranquility in Saxony.'),
('GermanHeritage', 'germanheritage@example.com', 'password39', 'Johannes Krämer', 'https://example.com/heritage.jpg', 'History and culture intertwined.'),
('MainzMagic', 'mainzmagic@example.com', 'password40', 'Theresa Herzog', 'https://example.com/mainz.jpg', 'Riverside festivals and fun.'),
('MecklenburgMoods', 'mecklenburg@example.com', 'password41', 'Tobias Peters', 'https://example.com/mecklenburg.jpg', 'Lakes, nature, and peace.'),
('MunichMeadow', 'munichmeadow@example.com', 'password42', 'Sophie Keller', 'https://example.com/meadow.jpg', 'Green spaces in the city.'),
('GermanSights', 'germansights@example.com', 'password43', 'Fabian Hoffmann', 'https://example.com/sights.jpg', 'Seeing it all.'),
('KarlsruheKing', 'karlsruhe@example.com', 'password44', 'Melanie Herzog', 'https://example.com/karlsruhe.jpg', 'Living near the Black Forest.'),
('GermanTrails', 'trails@example.com', 'password45', 'Jakob Kaiser', 'https://example.com/trails.jpg', 'Hiking across Germany.'),
('SchwäbischSoul', 'swabian@example.com', 'password46', 'Lisa Ziegler', 'https://example.com/swabian.jpg', 'Loving my Swabian roots.'),
('KielExplorer', 'kielexplorer@example.com', 'password47', 'Dennis Engel', 'https://example.com/kiel.jpg', 'Sailing through life.'),
('GermanGem', 'germangem@example.com', 'password48', 'Clara Brandt', 'https://example.com/gem.jpg', 'Finding hidden treasures.'),
('FreiburgFan', 'freiburgfan@example.com', 'password49', 'Michael Schmid', 'https://example.com/freiburg.jpg', 'Green energy and vibrant streets.'),

INSERT INTO users (username, email, password, full_name, profile_picture, bio) VALUES
('TokyoTraveler', 'tokyotraveler@example.com', 'password1', 'Haruto Tanaka', 'https://example.com/tokyo.jpg', 'Exploring Shibuya and Asakusa.'),
('KyotoDreamer', 'kyotodreamer@example.com', 'password2', 'Sakura Yamamoto', 'https://example.com/kyoto.jpg', 'Loving temples and cherry blossoms.'),
('OsakaEats', 'osakaeats@example.com', 'password3', 'Ren Sato', 'https://example.com/osaka.jpg', 'Takoyaki lover from Osaka.'),
('FukuokaFlavor', 'fukuokaflavor@example.com', 'password4', 'Yui Nakamura', 'https://example.com/fukuoka.jpg', 'Ramen enthusiast from Fukuoka.'),
('HokkaidoHiker', 'hokkaidohiker@example.com', 'password5', 'Kaito Suzuki', 'https://example.com/hokkaido.jpg', 'Hiking through snowy mountains.'),
('OkinawaOcean', 'okinawaocean@example.com', 'password6', 'Aoi Takahashi', 'https://example.com/okinawa.jpg', 'Island vibes and clear waters.'),
('ShinjukuShines', 'shinjukushines@example.com', 'password7', 'Riku Kobayashi', 'https://example.com/shinjuku.jpg', 'Neon lights and cityscapes.'),
('MountFujiFan', 'mountfujifan@example.com', 'password8', 'Hina Matsumoto', 'https://example.com/fuji.jpg', 'Climbing and admiring Mount Fuji.'),
('NagoyaNights', 'nagoyanights@example.com', 'password9', 'Souta Yamazaki', 'https://example.com/nagoya.jpg', 'Nightlife in Nagoya.'),
('KanazawaCulture', 'kanazawaculture@example.com', 'password10', 'Mei Shimizu', 'https://example.com/kanazawa.jpg', 'Art, tea, and tradition.'),
('KobeCuisine', 'kobecuisine@example.com', 'password11', 'Tsubasa Ishikawa', 'https://example.com/kobe.jpg', 'Loving Kobe beef and sweets.'),
('SendaiSpirit', 'sendaispirit@example.com', 'password12', 'Nao Kato', 'https://example.com/sendai.jpg', 'Festivals and fun in Sendai.'),
('HiroshimaHeart', 'hiroshimaheart@example.com', 'password13', 'Mao Fujimoto', 'https://example.com/hiroshima.jpg', 'Peace and history in Hiroshima.'),
('YokohamaYarns', 'yokohamayarns@example.com', 'password14', 'Itsuki Hayashi', 'https://example.com/yokohama.jpg', 'Portside views and adventures.'),
('SapporoSnow', 'sapporosnow@example.com', 'password15', 'Mikako Morita', 'https://example.com/sapporo.jpg', 'Loving the snow festival.'),
('NaraNature', 'naranature@example.com', 'password16', 'Daiki Okada', 'https://example.com/nara.jpg', 'Deer and serene temples.'),
('TokyoTales', 'tokyotales@example.com', 'password17', 'Hinata Ono', 'https://example.com/tales.jpg', 'Living the Tokyo life.'),
('KyushuKaleidoscope', 'kyushukaleidoscope@example.com', 'password18', 'Rin Yamada', 'https://example.com/kyushu.jpg', 'Colors and landscapes in Kyushu.'),
('ChibaCharm', 'chibacharm@example.com', 'password19', 'Takumi Fukuda', 'https://example.com/chiba.jpg', 'Riding waves and enjoying life.'),
('KumamotoCastle', 'kumamotocastle@example.com', 'password20', 'Misaki Arai', 'https://example.com/kumamoto.jpg', 'History and heritage in Kumamoto.'),
('TottoriTrails', 'tottoritrails@example.com', 'password21', 'Haruki Nishimura', 'https://example.com/tottori.jpg', 'Sand dunes and scenic hikes.'),
('NaganoNature', 'naganonature@example.com', 'password22', 'Sara Takeda', 'https://example.com/nagano.jpg', 'Skiing and hot springs.'),
('ShikokuSeeker', 'shikokuseeker@example.com', 'password23', 'Ryo Hasegawa', 'https://example.com/shikoku.jpg', 'Exploring Japan’s smallest island.'),
('KyotoKimonos', 'kyotokimonos@example.com', 'password24', 'Yuna Otsuka', 'https://example.com/kyoto_kimonos.jpg', 'Strolling in traditional attire.'),
('TokyoTrend', 'tokyotrend@example.com', 'password25', 'Sho Yamaguchi', 'https://example.com/trend.jpg', 'Fashion-forward Tokyoite.'),
('OsakaOdyssey', 'osakaodyssey@example.com', 'password26', 'Akari Taniguchi', 'https://example.com/odyssey.jpg', 'Urban adventures and culinary delights.'),
('HokkaidoHarmony', 'hokkaidoharmony@example.com', 'password27', 'Toma Matsuda', 'https://example.com/hokkaido.jpg', 'Peace and beauty in nature.'),
('OkinawaVibes', 'okinawavibes@example.com', 'password28', 'Riko Hashimoto', 'https://example.com/vibes.jpg', 'Ocean waves and sandy beaches.'),
('NikkoNostalgia', 'nikko@example.com', 'password29', 'Masaki Kitagawa', 'https://example.com/nikko.jpg', 'Exploring Toshogu Shrine.'),
('KyotoZen', 'kyotozen@example.com', 'password30', 'Kaori Takahashi', 'https://example.com/zen.jpg', 'Meditating in peaceful gardens.'),
('FukuokaFlavor', 'fukuokaflavor@example.com', 'password31', 'Hikaru Miura', 'https://example.com/fukuoka.jpg', 'Loving Tonkotsu ramen.'),
('OsakaDrift', 'osakadrift@example.com', 'password32', 'Kenta Ono', 'https://example.com/drift.jpg', 'Drifting through city lights.'),
('NagoyaNext', 'nagoyanext@example.com', 'password33', 'Minami Inoue', 'https://example.com/nagoya.jpg', 'Modern meets tradition in Nagoya.'),
('KamakuraKarma', 'kamakura@example.com', 'password34', 'Shinichi Yamashita', 'https://example.com/kamakura.jpg', 'Finding balance by the sea.'),
('HakoneHideaway', 'hakone@example.com', 'password35', 'Maya Nakagawa', 'https://example.com/hakone.jpg', 'Relaxing in hot springs.'),
('OsakaSoul', 'osakasoul@example.com', 'password36', 'Ryohei Morimoto', 'https://example.com/osaka.jpg', 'Heart of the Kansai region.'),
('TokyoShimmer', 'tokyoshimmer@example.com', 'password37', 'Kana Matsuda', 'https://example.com/shimmer.jpg', 'Living under city lights.'),
('HokkaidoExplorer', 'hokkaidoexplorer@example.com', 'password38', 'Yuuki Kondo', 'https://example.com/explorer.jpg', 'Roaming the northern wilds.'),
('NaraWisdom', 'narawisdom@example.com', 'password39', 'Reina Fujita', 'https://example.com/nara.jpg', 'Temples and tranquility.'),
('KyotoElegance', 'kyotoelegance@example.com', 'password40', 'Hinako Saeki', 'https://example.com/elegance.jpg', 'Grace and tradition in Kyoto.'),
('KobeWaves', 'kobewaves@example.com', 'password41', 'Shogo Yoshida', 'https://example.com/kobe.jpg', 'Seaside serenity in Kobe.'),
('HiroshimaHarmony', 'hiroshimaha@example.com', 'password42', 'Emi Kojima', 'https://example.com/harmony.jpg', 'Peaceful reflections in Hiroshima.'),
('OsakaLife', 'osakalife@example.com', 'password43', 'Sora Ueda', 'https://example.com/osakalife.jpg', 'Buzzy streets and food stalls.'),
('NaganoPeaks', 'naganofeaks@example.com', 'password44', 'Mari Ishikawa', 'https://example.com/peaks.jpg', 'Finding solace in the Alps.'),
('TokyoTwilight', 'tokyotwilight@example.com', 'password45', 'Eiji Sakamoto', 'https://example.com/twilight.jpg', 'Golden hours in Tokyo.'),
('OkinawaIsland', 'okinawaisland@example.com', 'password46', 'Ayumi Kurata', 'https://example.com/island.jpg', 'Tropical living in paradise.'),
('JapaneseSoul', 'japanesesoul@example.com', 'password47', 'Keita Sasaki', 'https://example.com/soul.jpg', 'Capturing the essence of Japan.'),
('HiroshimaLight', 'hiroshimalight@example.com', 'password48', 'Miki Oda', 'https://example.com/light.jpg', 'Lantern festivals and hope.'),
('TokyoSerene', 'tokyosere@example.com', 'password49', 'Naoki Itō', 'https://example.com/serene.jpg', 'Gentle life under Tokyo bustle.'),
('OkinawanSea', 'okinawasea@example.com', 'password50', 'Ruri Endo', 'https://example.com/sea.jpg', 'Admiring coral reefs.'); 

