-- Insert sample users
INSERT INTO users (username, email, password, full_name, profile_picture, bio) VALUES
('user1', 'user1@example.com', 'password1', 'User One', 'https://example.com/user1.jpg', 'Bio of User One'),
('user2', 'user2@example.com', 'password2', 'User Two', 'https://example.com/user2.jpg', 'Bio of User Two'),
('user3', 'user3@example.com', 'password3', 'User Three', 'https://example.com/user3.jpg', 'Bio of User Three'),
('user4', 'user20@example.com', 'password4', 'User Four', 'https://example.com/user4.jpg', 'Bio of User Four'),
('PixelPenguin', 'penguin@example.com', 'password5', 'Arctic Wanderer', 'https://example.com/penguin.jpg', 'Lover of cold vibes and pixels.'),
('SkyChaser', 'sky@example.com', 'password6', 'Skyline Dreamer', 'https://example.com/sky.jpg', 'Capturing the horizons, one photo at a time.'),
('MountainGoat', 'goat@example.com', 'password7', 'Rocky Trails', 'https://example.com/goat.jpg', 'Explorer of cliffs and peaks.'),
('RiverWanderer', 'river@example.com', 'password8', 'Flowing Spirit', 'https://example.com/river.jpg', 'Serenity found in the stream.'),
('DesertFox', 'fox@example.com', 'password9', 'Sahara Rover', 'https://example.com/fox.jpg', 'Finding life in the desert.'),
('TechTrekker', 'techtrekker@example.com', 'password10', 'Digital Nomad', 'https://example.com/trekker.jpg', 'Exploring the world of innovation.');

INSERT INTO users (username, email, password, full_name, profile_picture, bio) VALUES
('TeaLover', 'tea@example.com', 'password1', 'Elizabeth Green', 'https://example.com/tea.jpg', 'Afternoon tea enthusiast.'),
('LondonWalker', 'walker@example.com', 'password2', 'John Sterling', 'https://example.com/london.jpg', 'Exploring the streets of London.'),
('BiscuitHunter', 'biscuit@example.com', 'password3', 'Margaret Brown', 'https://example.com/biscuit.jpg', 'In search of the perfect biscuit.'),
('FoggyMorning', 'foggy@example.com', 'password4', 'Edward Grey', 'https://example.com/foggy.jpg', 'Misty mornings and coffee cups.'),
('ShakespeareFan', 'shakespeare@example.com', 'password5', 'William Page', 'https://example.com/shakespeare.jpg', 'To be or not to be!'),
('UnionJack', 'unionjack@example.com', 'password6', 'Victoria Redford', 'https://example.com/unionjack.jpg', 'Flying the flag with pride.'),
('ThamesRider', 'thames@example.com', 'password7', 'Arthur Lake', 'https://example.com/thames.jpg', 'Cruising down the Thames.'),
('BigBenBeliever', 'bigben@example.com', 'password8', 'Benjamin Clock', 'https://example.com/bigben.jpg', 'Tick-tock through time.'),
('RoyalGardener', 'royalgardener@example.com', 'password9', 'Catherine Bloom', 'https://example.com/garden.jpg', 'Green thumb with a royal touch.'),
('RainyDayDreamer', 'rainyday@example.com', 'password10', 'Harold Weatherby', 'https://example.com/rainyday.jpg', 'Dreaming in the rain.'),
('BoroughBaker', 'baker@example.com', 'password11', 'Sarah Loaf', 'https://example.com/bakery.jpg', 'Bread, pies, and everything nice.'),
('TowerBridgeTrekker', 'towerbridge@example.com', 'password12', 'Daniel Stone', 'https://example.com/towerbridge.jpg', 'Lover of iconic bridges.'),
('PubExplorer', 'pub@example.com', 'password13', 'George Aleman', 'https://example.com/pub.jpg', 'Searching for the coziest pubs.'),
('CambridgeScholar', 'cambridge@example.com', 'password14', 'Emily King', 'https://example.com/cambridge.jpg', 'Books, learning, and tea.'),
('RedBusRider', 'redbus@example.com', 'password15', 'Charles Wheels', 'https://example.com/redbus.jpg', 'Hopping on and off in style.'),
('CountrysideChaser', 'countryside@example.com', 'password16', 'Lydia Fields', 'https://example.com/countryside.jpg', 'The hills are alive with beauty.'),
('CricketFanatic', 'cricket@example.com', 'password17', 'James Batson', 'https://example.com/cricket.jpg', 'Bowled over by cricket.'),
('CottageCoreDream', 'cottagecore@example.com', 'password18', 'Alice Meadow', 'https://example.com/cottage.jpg', 'Rustic charm, always.'),
('StonehengeSeeker', 'stonehenge@example.com', 'password19', 'Oliver Circle', 'https://example.com/stonehenge.jpg', 'Mysteries of the ancient stones.'),
('OxfordThinker', 'oxford@example.com', 'password20', 'Henry Brainwood', 'https://example.com/oxford.jpg', 'Wisdom in the dreaming spires.'),
('TeaAndBooks', 'teaandbooks@example.com', 'password21', 'Charlotte Turner', 'https://example.com/teaandbooks.jpg', 'Perfect pairing: tea and novels.'),
('CozyFireplace', 'fireplace@example.com', 'password22', 'Lucy Warmth', 'https://example.com/fireplace.jpg', 'Fireside chats and marshmallows.'),
('CastlesAndCrowns', 'castles@example.com', 'password23', 'Philip Crownstone', 'https://example.com/castles.jpg', 'History and grandeur everywhere.'),
('LakeDistrictLover', 'lakedistrict@example.com', 'password24', 'Anna Waters', 'https://example.com/lakedistrict.jpg', 'The lakes are my happy place.'),
('YorkshirePudding', 'yorkshire@example.com', 'password25', 'Frederick Tasty', 'https://example.com/yorkshire.jpg', 'Foodie with a northern twist.'),
('ScottishHighlander', 'scottish@example.com', 'password26', 'Fiona Braveheart', 'https://example.com/highlands.jpg', 'Mountains and misty glens.'),
('CharmingChelsea', 'chelsea@example.com', 'password27', 'Sophia Lane', 'https://example.com/chelsea.jpg', 'Exploring stylish corners.'),
('GreenwichGazer', 'greenwich@example.com', 'password28', 'Samuel Time', 'https://example.com/greenwich.jpg', 'Setting my clock to Greenwich Mean Time.'),
('BuckinghamDreamer', 'buckingham@example.com', 'password29', 'Diana Windsor', 'https://example.com/buckingham.jpg', 'Palaces, gardens, and dreams.'),
('HamptonHistorian', 'hampton@example.com', 'password30', 'Edward Hall', 'https://example.com/hampton.jpg', 'Timeless tales from the court.'),
('QueenBee', 'queenbee@example.com', 'password31', 'Victoria Majesty', 'https://example.com/queenbee.jpg', 'Ruling my little kingdom.'),
('RegentStroller', 'regent@example.com', 'password32', 'Alexander Lane', 'https://example.com/regent.jpg', 'Walking through history.'),
('PortobelloPicker', 'portobello@example.com', 'password33', 'Amelia Market', 'https://example.com/portobello.jpg', 'Finding treasures in the market.'),
('HydeParkJogger', 'hydepark@example.com', 'password34', 'Thomas Sprint', 'https://example.com/hydepark.jpg', 'Running through iconic views.'),
('VintageVictoria', 'vintagevictoria@example.com', 'password35', 'Emily Lace', 'https://example.com/vintage.jpg', 'Timeless and elegant always.'),
('LondonEyeSeer', 'londoneye@example.com', 'password36', 'Eleanor View', 'https://example.com/londoneye.jpg', 'Seeing the city from above.'),
('RoyalTeaParty', 'royalteaparty@example.com', 'password37', 'Isabelle Cup', 'https://example.com/teaparty.jpg', 'Sipping tea with a twist.'),
('AbbeyFanatic', 'abbey@example.com', 'password38', 'Matthew Bells', 'https://example.com/abbey.jpg', 'Echoes of history in stone.'),
('LakePoet', 'lakepoet@example.com', 'password39', 'Dorothy Wordsworth', 'https://example.com/lakepoet.jpg', 'Writing in the stillness.'),
('EnglishRose', 'rose@example.com', 'password40', 'Rosemary Petals', 'https://example.com/rose.jpg', 'Blooms of inspiration.'),
('VictorianVibes', 'victorianvibes@example.com', 'password41', 'Arthur Dickens', 'https://example.com/victorian.jpg', 'A step back in time.'),
('HedgehogLover', 'hedgehog@example.com', 'password42', 'Hannah Prickles', 'https://example.com/hedgehog.jpg', 'Nature’s little wonders.'),
('ThistleAndThames', 'thistleandthames@example.com', 'password43', 'William Scott', 'https://example.com/thistle.jpg', 'A blend of north and south.'),
('CountryLane', 'countrylane@example.com', 'password44', 'Laura Fielding', 'https://example.com/countrylane.jpg', 'The winding roads of beauty.'),
('LondonLights', 'londonlights@example.com', 'password45', 'Olivia Glow', 'https://example.com/londonlights.jpg', 'Bright nights in the city.'),
('CamdenCrafter', 'camden@example.com', 'password46', 'Daniel Crafton', 'https://example.com/camden.jpg', 'Creative vibes in the market.'),
('GreenFields', 'greenfields@example.com', 'password47', 'Emily Clover', 'https://example.com/greenfields.jpg', 'Rolling hills forever.'),
('RainyUmbrella', 'umbrella@example.com', 'password48', 'Harry Weather', 'https://example.com/umbrella.jpg', 'Under my umbrella.'),
('DoverExplorer', 'dover@example.com', 'password49', 'Christopher Cliff', 'https://example.com/dover.jpg', 'White cliffs and blue seas.'),
('BristolBridges', 'bristol@example.com', 'password50', 'Charlotte Spans', 'https://example.com/bristol.jpg', 'Connecting the dots.');
