-- Insert sample users
INSERT INTO users (username, email, password, full_name, profile_picture, bio) VALUES
('user1', 'user1@example.com', 'password1', 'User One', 'https://example.com/user1.jpg', 'Bio of User One'),
('user2', 'user2@example.com', 'password2', 'User Two', 'https://example.com/user2.jpg', 'Bio of User Two'),
('user3', 'user3@example.com', 'password3', 'User Three', 'https://example.com/user3.jpg', 'Bio of User Three'),
('user4', 'user20@example.com', 'password4', 'User Four', 'https://example.com/user4.jpg', 'Bio of User Four'),
('PixelPenguin', 'penguin@example.com', 'password5', 'Arctic Wanderer', 'https://example.com/penguin.jpg', 'Lover of cold vibes and pixels.'),
('SkyChaser', 'sky@example.com', 'password6', 'Skyline Dreamer', 'https://example.com/sky.jpg', 'Capturing the horizons, one photo at a time.'),
('MountainGoat', 'goat@example.com', 'password7', 'Rocky Trails', 'https://example.com/goat.jpg', 'Explorer of cliffs and peaks.'),
('RiverWanderer', 'river@example.com', 'password8', 'Flowing Spirit', 'https://example.com/river.jpg', 'Serenity found in the stream.'),
('DesertFox', 'fox@example.com', 'password9', 'Sahara Rover', 'https://example.com/fox.jpg', 'Finding life in the desert.'),
('TechTrekker', 'techtrekker@example.com', 'password10', 'Digital Nomad', 'https://example.com/trekker.jpg', 'Exploring the world of innovation.');

INSERT INTO users (username, email, password, full_name, profile_picture, bio) VALUES
('TeaLover', 'tea@example.com', 'password1', 'Elizabeth Green', 'https://example.com/tea.jpg', 'Afternoon tea enthusiast.'),
('LondonWalker', 'walker@example.com', 'password2', 'John Sterling', 'https://example.com/london.jpg', 'Exploring the streets of London.'),
('BiscuitHunter', 'biscuit@example.com', 'password3', 'Margaret Brown', 'https://example.com/biscuit.jpg', 'In search of the perfect biscuit.'),
('FoggyMorning', 'foggy@example.com', 'password4', 'Edward Grey', 'https://example.com/foggy.jpg', 'Misty mornings and coffee cups.'),
('ShakespeareFan', 'shakespeare@example.com', 'password5', 'William Page', 'https://example.com/shakespeare.jpg', 'To be or not to be!'),
('UnionJack', 'unionjack@example.com', 'password6', 'Victoria Redford', 'https://example.com/unionjack.jpg', 'Flying the flag with pride.'),
('ThamesRider', 'thames@example.com', 'password7', 'Arthur Lake', 'https://example.com/thames.jpg', 'Cruising down the Thames.'),
('BigBenBeliever', 'bigben@example.com', 'password8', 'Benjamin Clock', 'https://example.com/bigben.jpg', 'Tick-tock through time.'),
('RoyalGardener', 'royalgardener@example.com', 'password9', 'Catherine Bloom', 'https://example.com/garden.jpg', 'Green thumb with a royal touch.'),
('RainyDayDreamer', 'rainyday@example.com', 'password10', 'Harold Weatherby', 'https://example.com/rainyday.jpg', 'Dreaming in the rain.'),
('BoroughBaker', 'baker@example.com', 'password11', 'Sarah Loaf', 'https://example.com/bakery.jpg', 'Bread, pies, and everything nice.'),
('TowerBridgeTrekker', 'towerbridge@example.com', 'password12', 'Daniel Stone', 'https://example.com/towerbridge.jpg', 'Lover of iconic bridges.'),
('PubExplorer', 'pub@example.com', 'password13', 'George Aleman', 'https://example.com/pub.jpg', 'Searching for the coziest pubs.'),
('CambridgeScholar', 'cambridge@example.com', 'password14', 'Emily King', 'https://example.com/cambridge.jpg', 'Books, learning, and tea.'),
('RedBusRider', 'redbus@example.com', 'password15', 'Charles Wheels', 'https://example.com/redbus.jpg', 'Hopping on and off in style.'),
('CountrysideChaser', 'countryside@example.com', 'password16', 'Lydia Fields', 'https://example.com/countryside.jpg', 'The hills are alive with beauty.'),
('CricketFanatic', 'cricket@example.com', 'password17', 'James Batson', 'https://example.com/cricket.jpg', 'Bowled over by cricket.'),
('CottageCoreDream', 'cottagecore@example.com', 'password18', 'Alice Meadow', 'https://example.com/cottage.jpg', 'Rustic charm, always.'),
('StonehengeSeeker', 'stonehenge@example.com', 'password19', 'Oliver Circle', 'https://example.com/stonehenge.jpg', 'Mysteries of the ancient stones.'),
('OxfordThinker', 'oxford@example.com', 'password20', 'Henry Brainwood', 'https://example.com/oxford.jpg', 'Wisdom in the dreaming spires.'),
('TeaAndBooks', 'teaandbooks@example.com', 'password21', 'Charlotte Turner', 'https://example.com/teaandbooks.jpg', 'Perfect pairing: tea and novels.'),
('CozyFireplace', 'fireplace@example.com', 'password22', 'Lucy Warmth', 'https://example.com/fireplace.jpg', 'Fireside chats and marshmallows.'),
('CastlesAndCrowns', 'castles@example.com', 'password23', 'Philip Crownstone', 'https://example.com/castles.jpg', 'History and grandeur everywhere.'),
('LakeDistrictLover', 'lakedistrict@example.com', 'password24', 'Anna Waters', 'https://example.com/lakedistrict.jpg', 'The lakes are my happy place.'),
('YorkshirePudding', 'yorkshire@example.com', 'password25', 'Frederick Tasty', 'https://example.com/yorkshire.jpg', 'Foodie with a northern twist.'),
('ScottishHighlander', 'scottish@example.com', 'password26', 'Fiona Braveheart', 'https://example.com/highlands.jpg', 'Mountains and misty glens.'),
('CharmingChelsea', 'chelsea@example.com', 'password27', 'Sophia Lane', 'https://example.com/chelsea.jpg', 'Exploring stylish corners.'),
('GreenwichGazer', 'greenwich@example.com', 'password28', 'Samuel Time', 'https://example.com/greenwich.jpg', 'Setting my clock to Greenwich Mean Time.'),
('BuckinghamDreamer', 'buckingham@example.com', 'password29', 'Diana Windsor', 'https://example.com/buckingham.jpg', 'Palaces, gardens, and dreams.'),
('HamptonHistorian', 'hampton@example.com', 'password30', 'Edward Hall', 'https://example.com/hampton.jpg', 'Timeless tales from the court.'),
('QueenBee', 'queenbee@example.com', 'password31', 'Victoria Majesty', 'https://example.com/queenbee.jpg', 'Ruling my little kingdom.'),
('RegentStroller', 'regent@example.com', 'password32', 'Alexander Lane', 'https://example.com/regent.jpg', 'Walking through history.'),
('PortobelloPicker', 'portobello@example.com', 'password33', 'Amelia Market', 'https://example.com/portobello.jpg', 'Finding treasures in the market.'),
('HydeParkJogger', 'hydepark@example.com', 'password34', 'Thomas Sprint', 'https://example.com/hydepark.jpg', 'Running through iconic views.'),
('VintageVictoria', 'vintagevictoria@example.com', 'password35', 'Emily Lace', 'https://example.com/vintage.jpg', 'Timeless and elegant always.'),
('LondonEyeSeer', 'londoneye@example.com', 'password36', 'Eleanor View', 'https://example.com/londoneye.jpg', 'Seeing the city from above.'),
('RoyalTeaParty', 'royalteaparty@example.com', 'password37', 'Isabelle Cup', 'https://example.com/teaparty.jpg', 'Sipping tea with a twist.'),
('AbbeyFanatic', 'abbey@example.com', 'password38', 'Matthew Bells', 'https://example.com/abbey.jpg', 'Echoes of history in stone.'),
('LakePoet', 'lakepoet@example.com', 'password39', 'Dorothy Wordsworth', 'https://example.com/lakepoet.jpg', 'Writing in the stillness.'),
('EnglishRose', 'rose@example.com', 'password40', 'Rosemary Petals', 'https://example.com/rose.jpg', 'Blooms of inspiration.'),
('VictorianVibes', 'victorianvibes@example.com', 'password41', 'Arthur Dickens', 'https://example.com/victorian.jpg', 'A step back in time.'),
('HedgehogLover', 'hedgehog@example.com', 'password42', 'Hannah Prickles', 'https://example.com/hedgehog.jpg', 'Nature’s little wonders.'),
('ThistleAndThames', 'thistleandthames@example.com', 'password43', 'William Scott', 'https://example.com/thistle.jpg', 'A blend of north and south.'),
('CountryLane', 'countrylane@example.com', 'password44', 'Laura Fielding', 'https://example.com/countrylane.jpg', 'The winding roads of beauty.'),
('LondonLights', 'londonlights@example.com', 'password45', 'Olivia Glow', 'https://example.com/londonlights.jpg', 'Bright nights in the city.'),
('CamdenCrafter', 'camden@example.com', 'password46', 'Daniel Crafton', 'https://example.com/camden.jpg', 'Creative vibes in the market.'),
('GreenFields', 'greenfields@example.com', 'password47', 'Emily Clover', 'https://example.com/greenfields.jpg', 'Rolling hills forever.'),
('RainyUmbrella', 'umbrella@example.com', 'password48', 'Harry Weather', 'https://example.com/umbrella.jpg', 'Under my umbrella.'),
('DoverExplorer', 'dover@example.com', 'password49', 'Christopher Cliff', 'https://example.com/dover.jpg', 'White cliffs and blue seas.'),
('BristolBridges', 'bristol@example.com', 'password50', 'Charlotte Spans', 'https://example.com/bristol.jpg', 'Connecting the dots.');

INSERT INTO users (username, email, password, full_name, profile_picture, bio) VALUES
('StarsAndStripes', 'stars@example.com', 'password1', 'Samuel Freedom', 'https://example.com/stars.jpg', 'Patriot at heart.'),
('NYCPizzaLover', 'pizza@example.com', 'password2', 'Alex Brooklyn', 'https://example.com/pizza.jpg', 'In crust we trust.'),
('Route66Rider', 'route66@example.com', 'password3', 'Chris Highway', 'https://example.com/route66.jpg', 'Riding the American dream.'),
('GoldenGateGazer', 'goldengate@example.com', 'password4', 'Samantha Bridge', 'https://example.com/goldengate.jpg', 'Views from the bridge.'),
('BBQKing', 'bbqking@example.com', 'password5', 'Jordan Smoke', 'https://example.com/bbq.jpg', 'Meat, fire, and flavor.'),
('TexasRancher', 'texas@example.com', 'password6', 'Taylor Lasso', 'https://example.com/texas.jpg', 'Hats, boots, and sunsets.'),
('CaliforniaDreamer', 'californiadreamer@example.com', 'password7', 'Jessica Malibu', 'https://example.com/california.jpg', 'Beach days and starry nights.'),
('LibertyBellFan', 'libertybell@example.com', 'password8', 'Franklin Bell', 'https://example.com/libertybell.jpg', 'Ringing in freedom.'),
('MiamiSunshine', 'miamisunshine@example.com', 'password9', 'Sophia Ocean', 'https://example.com/miami.jpg', 'Living for the waves.'),
('AlaskaExplorer', 'alaska@example.com', 'password10', 'Hannah Glacier', 'https://example.com/alaska.jpg', 'Chasing northern lights.'),
('ChicagoDeepDish', 'deepdish@example.com', 'password11', 'Matthew Slice', 'https://example.com/deepdish.jpg', 'Windy city foodie.'),
('GrandCanyonHiker', 'grandcanyon@example.com', 'password12', 'Bryan Canyon', 'https://example.com/grandcanyon.jpg', 'The edge of wonder.'),
('JazzAndBeignets', 'jazz@example.com', 'password13', 'Lila NewOrleans', 'https://example.com/jazz.jpg', 'Sweet tunes and sweeter treats.'),
('SeattleBrews', 'seattle@example.com', 'password14', 'Ethan Coffee', 'https://example.com/seattle.jpg', 'Caffeine and rain.'),
('RockyMountainClimber', 'rockies@example.com', 'password15', 'Emily Peak', 'https://example.com/rockies.jpg', 'Adventure is out there.'),
('DisneyFanatic', 'disney@example.com', 'password16', 'Mickey Fan', 'https://example.com/disney.jpg', 'Magic is everywhere.'),
('SouthernCharm', 'southern@example.com', 'password17', 'Charlotte Savannah', 'https://example.com/southern.jpg', 'Y’all come back now.'),
('YosemiteWanderer', 'yosemite@example.com', 'password18', 'Jack Valley', 'https://example.com/yosemite.jpg', 'Lost in nature.'),
('HollywoodDreamer', 'hollywood@example.com', 'password19', 'Taylor Lights', 'https://example.com/hollywood.jpg', 'Roll the credits.'),
('VegasLights', 'vegaslights@example.com', 'password20', 'Cassidy Jackpot', 'https://example.com/vegas.jpg', 'Bright lights, big city.'),
('BroadwayStar', 'broadway@example.com', 'password21', 'Ella Spotlight', 'https://example.com/broadway.jpg', 'The stage is set.'),
('SiliconValleyTech', 'siliconvalley@example.com', 'password22', 'Logan Code', 'https://example.com/siliconvalley.jpg', 'Innovation is my passion.'),
('TennesseeWhiskey', 'whiskey@example.com', 'password23', 'Lucas Distiller', 'https://example.com/whiskey.jpg', 'Smooth as Tennessee.'),
('CapeCodCruiser', 'capecod@example.com', 'password24', 'Isabella Harbor', 'https://example.com/capecod.jpg', 'Sailing through the breeze.'),
('HawaiiAloha', 'hawaii@example.com', 'password25', 'Noah Wave', 'https://example.com/hawaii.jpg', 'Aloha vibes only.'),
('StatueOfLiberty', 'statueofliberty@example.com', 'password26', 'Grace Ellis', 'https://example.com/statueofliberty.jpg', 'Beacon of freedom.'),
('CowboyBoots', 'cowboyboots@example.com', 'password27', 'Riley Spurs', 'https://example.com/cowboyboots.jpg', 'Giddy up, partner.'),
('BostonRedSox', 'redsox@example.com', 'password28', 'Elliot Fenway', 'https://example.com/redsox.jpg', 'Baseball and chowder.'),
('SmokyMountainView', 'smokymountains@example.com', 'password29', 'Jasmine Mist', 'https://example.com/smokies.jpg', 'Foggy horizons forever.'),
('SpaceCenterFan', 'spacecenter@example.com', 'password30', 'Caleb Apollo', 'https://example.com/spacecenter.jpg', 'Houston, we have liftoff.'),
('FloridaKeysSunset', 'floridakeys@example.com', 'password31', 'Savannah Horizon', 'https://example.com/floridakeys.jpg', 'Sunset chaser.'),
('NiagaraFalls', 'niagara@example.com', 'password32', 'Daniel Splash', 'https://example.com/niagara.jpg', 'Roaring waters ahead.'),
('TexasBBQLover', 'texasbbq@example.com', 'password33', 'Jaxon Smoke', 'https://example.com/texasbbq.jpg', 'Barbecue is life.'),
('BayAreaBiker', 'bayarea@example.com', 'password34', 'Sierra Pedals', 'https://example.com/bayarea.jpg', 'Rolling through the hills.'),
('DenverBrews', 'denver@example.com', 'password35', 'Hunter Craft', 'https://example.com/denver.jpg', 'Cheers to craft beer.'),
('YellowstoneExplorer', 'yellowstone@example.com', 'password36', 'Ella Geyser', 'https://example.com/yellowstone.jpg', 'Nature at its finest.'),
('SaltLakeSkier', 'saltlake@example.com', 'password37', 'Mason Snow', 'https://example.com/snow.jpg', 'Powder days forever.'),
('PhoenixRising', 'phoenix@example.com', 'password38', 'Avery Blaze', 'https://example.com/phoenix.jpg', 'Heat and heart.'),
('CaliSurfer', 'calisurfer@example.com', 'password39', 'Brandon Wave', 'https://example.com/surf.jpg', 'Catch the perfect wave.'),
('BostonTeaParty', 'bostontea@example.com', 'password40', 'Emily Harbor', 'https://example.com/boston.jpg', 'Revolutionary vibes.'),
('KeyWestChill', 'keywest@example.com', 'password41', 'Harper Tides', 'https://example.com/keywest.jpg', 'Island life forever.'),
('NashvilleStrings', 'nashville@example.com', 'password42', 'Madison Harmony', 'https://example.com/nashville.jpg', 'Music is my soul.'),
('AlamoAdventurer', 'alamo@example.com', 'password43', 'Declan Remember', 'https://example.com/alamo.jpg', 'History and bravery.'),
('MinneapolisLakes', 'minneapolis@example.com', 'password44', 'Autumn North', 'https://example.com/minneapolis.jpg', 'Land of 10,000 lakes.'),
('SedonaHiker', 'sedona@example.com', 'password45', 'Ruby Canyon', 'https://example.com/sedona.jpg', 'Red rock wonderland.'),
('WashingtonApple', 'washington@example.com', 'password46', 'Grace Orchard', 'https://example.com/washington.jpg', 'An apple a day.'),
('BigSkyDreamer', 'bigsky@example.com', 'password47', 'Skyler Montana', 'https://example.com/bigsky.jpg', 'Under the endless sky.'),
('MountRushmore', 'mountrushmore@example.com', 'password48', 'Parker Presidents', 'https://example.com/rushmore.jpg', 'Carving memories.'),
('OregonTrails', 'oregon@example.com', 'password49', 'Dakota River', 'https://example.com/oregon.jpg', 'The great journey west.'),
('ZionAdventurer', 'zion@example.com', 'password50', 'Jordan Cliff', 'https://example.com/zion.jpg', 'Scaling new heights.');

