# Generated by Django 6.0.2 on 2026-03-01 17:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('customer_type', models.CharField(choices=[('LOCAL', 'Local Resident'), ('VISITOR', 'Visitor')], default='VISITOR', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('GAS', 'Gas'), ('CAR', 'Car Maintenance'), ('ADS', 'Advertising'), ('TAX', 'Taxes'), ('MAT', 'Yoga Mats'), ('OTHER', 'Other')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(default='Yoga Mat', max_length=100)),
                ('purchase_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=6)),
                ('expected_lifetime_years', models.FloatField(default=1.5)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField(default='09:00')),
                ('max_students', models.IntegerField(default=20)),
                ('min_students', models.IntegerField(default=3)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('attendees', models.ManyToManyField(blank=True, related_name='lessons_attended', to='core.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_lessons', models.IntegerField(choices=[(1, 'Single Lesson - 15€'), (3, '3 Lessons - 40€'), (5, '5 Lessons - 50€'), (10, '10 Lessons - 100€')])),
                ('remaining_lessons', models.IntegerField()),
                ('purchase_date', models.DateField(default=django.utils.timezone.now)),
                ('price_paid', models.DecimalField(decimal_places=2, max_digits=6)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='core.customer')),
            ],
        ),
    ]
