# Generated by Django 6.0.2 on 2026-04-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customer_city_customer_country_customer_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('YOGA', 'Yoga'), ('MEDITATION', 'Meditation')], default='YOGA', max_length=20),
        ),
        migrations.AddField(
            model_name='package',
            name='package_type',
            field=models.CharField(choices=[('YOGA', 'Yoga'), ('MEDITATION', 'Meditation')], default='YOGA', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('GAS', 'Gas'), ('CAR', 'Car Maintenance'), ('ADS', 'Advertising'), ('TAX', 'Taxes (IVA/IRPF)'), ('SOCIAL', 'Social Security'), ('INSURANCE', 'Insurance'), ('MAT', 'Yoga Mats'), ('OTHER', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='package',
            name='total_lessons',
            field=models.IntegerField(),
        ),
    ]
